// Generated by scripts/freeze-legacy-defaults.mjs from ee171d2a, the last build deployed before saves
// said what follows the defaults. Don't edit it, and don't regenerate it from a newer commit: it's
// frozen on purpose (docs/architecture.md "Following the defaults"), so a save holding these defaults
// keeps migrating however the defaults change later.
import type { GearSlot, SpecId } from '@/sim'

/** A slot's item and enchant, as [itemId] or [itemId, enchantId]. */
export type LegacyEntry = readonly [number] | readonly [number, string]

/** One spec's defaults at ee171d2a. */
export interface LegacySpecDefaults {
  /** The class's default race. */
  race: string
  /** The default talent build. */
  talents: string
  /** The distinct gear sets, normalized as a loaded setup holds them. */
  sets: readonly Partial<Record<GearSlot, LegacyEntry>>[]
  /** Per race the class can be: [its default gear, v1's pick (the pre-raid lists alone)], as indices into `sets`. */
  races: Readonly<Record<string, readonly [number, number]>>
}

export const LEGACY_COMMIT = 'ee171d2a'

export const LEGACY_DEFAULTS: Readonly<Partial<Record<SpecId, LegacySpecDefaults>>> = {
  'warrior-fury': {
    race: 'alliance-human',
    talents: '30305013002-050530035150010051-',
    sets: [
      { head: [12640, 'arcanumVoracityStrength'], neck: [15411, 'neckStrength'], shoulder: [23243], back: [13340, 'cloakAgility'], chest: [11726, 'chestGreaterStats'], wrist: [12936, 'bracerSuperiorStrength'], hands: [15063, 'gloveGreaterStrength'], waist: [13142], legs: [15062, 'arcanumVoracityStrength'], feet: [22858, 'bootsGreaterAgility'], ranged: [18323], finger1: [19325], finger2: [18500], trinket1: [11815], trinket2: [13965], mainHand: [11684, 'crusader'], offHand: [15806, 'crusader'] },
      { head: [12640, 'arcanumVoracityStrength'], neck: [15411, 'neckStrength'], shoulder: [23315], back: [13340, 'cloakAgility'], chest: [11726, 'chestGreaterStats'], wrist: [12936, 'bracerSuperiorStrength'], hands: [15063, 'gloveGreaterStrength'], waist: [13142], legs: [15062, 'arcanumVoracityStrength'], feet: [23287, 'bootsGreaterAgility'], ranged: [18323], finger1: [19325], finger2: [18500], trinket1: [11815], trinket2: [13965], mainHand: [11684, 'crusader'], offHand: [15806, 'crusader'] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-tauren': [0, 0], 'horde-troll': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-human': [1, 1], 'alliance-dwarf': [1, 1], 'alliance-night-elf': [1, 1], 'alliance-gnome': [1, 1], 'alliance-skyborne-high-order': [1, 1] },
  },
  'warrior-arms': {
    race: 'alliance-human',
    talents: '30305213132515201-05050103-',
    sets: [
      { head: [12640, 'arcanumVoracityStrength'], neck: [15411, 'neckStrength'], shoulder: [23243], back: [13340, 'cloakAgility'], chest: [11726, 'chestGreaterStats'], wrist: [12936, 'bracerSuperiorStrength'], hands: [15063, 'gloveGreaterStrength'], waist: [13142], legs: [15062, 'arcanumVoracityStrength'], feet: [22858, 'bootsGreaterAgility'], ranged: [18323], finger1: [19325], finger2: [18500], trinket1: [11815], trinket2: [13965], mainHand: [12592, 'crusader'] },
      { head: [12640, 'arcanumVoracityStrength'], neck: [15411, 'neckStrength'], shoulder: [23315], back: [13340, 'cloakAgility'], chest: [11726, 'chestGreaterStats'], wrist: [12936, 'bracerSuperiorStrength'], hands: [15063, 'gloveGreaterStrength'], waist: [13142], legs: [15062, 'arcanumVoracityStrength'], feet: [23287, 'bootsGreaterAgility'], ranged: [18323], finger1: [19325], finger2: [18500], trinket1: [11815], trinket2: [13965], mainHand: [12592, 'crusader'] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-tauren': [0, 0], 'horde-troll': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-human': [1, 1], 'alliance-dwarf': [1, 1], 'alliance-night-elf': [1, 1], 'alliance-gnome': [1, 1], 'alliance-skyborne-high-order': [1, 1] },
  },
  'warrior-protection': {
    race: 'alliance-human',
    talents: '35-05-552101233301210531',
    sets: [
      { head: [12640, 'arcanumVoracityStrength'], neck: [22340, 'neckStrength'], shoulder: [19695], back: [21187, 'cloakAgility'], chest: [22872, 'chestGreaterStats'], wrist: [13400, 'bracerSuperiorStrength'], hands: [18722, 'gloveThreat'], waist: [13142], legs: [22873, 'arcanumVoracityStrength'], feet: [22858, 'bootsGreaterAgility'], ranged: [18323], finger1: [19325], finger2: [275971], trinket1: [272437], trinket2: [11815], mainHand: [2244, 'crusader'], offHand: [18756, 'shieldGreaterStamina'] },
      { head: [12640, 'arcanumVoracityStrength'], neck: [13091, 'neckStrength'], shoulder: [23243], back: [13397, 'cloakAgility'], chest: [22872, 'chestGreaterStats'], wrist: [16735, 'bracerSuperiorStrength'], hands: [14525, 'gloveThreat'], waist: [13142], legs: [14554, 'arcanumVoracityStrength'], feet: [22858, 'bootsGreaterAgility'], ranged: [18323], finger1: [19325], finger2: [2246], trinket1: [11815], trinket2: [17774], mainHand: [15806, 'crusader'], offHand: [12602, 'shieldGreaterStamina'] },
      { head: [12640, 'arcanumVoracityStrength'], neck: [22340, 'neckStrength'], shoulder: [19695], back: [21187, 'cloakAgility'], chest: [23300, 'chestGreaterStats'], wrist: [13400, 'bracerSuperiorStrength'], hands: [18722, 'gloveThreat'], waist: [13142], legs: [23301, 'arcanumVoracityStrength'], feet: [23287, 'bootsGreaterAgility'], ranged: [18323], finger1: [19325], finger2: [275971], trinket1: [272437], trinket2: [11815], mainHand: [2244, 'crusader'], offHand: [18756, 'shieldGreaterStamina'] },
      { head: [12640, 'arcanumVoracityStrength'], neck: [13091, 'neckStrength'], shoulder: [23315], back: [13397, 'cloakAgility'], chest: [23300, 'chestGreaterStats'], wrist: [16735, 'bracerSuperiorStrength'], hands: [14525, 'gloveThreat'], waist: [13142], legs: [14554, 'arcanumVoracityStrength'], feet: [23287, 'bootsGreaterAgility'], ranged: [18323], finger1: [19325], finger2: [2246], trinket1: [11815], trinket2: [17774], mainHand: [15806, 'crusader'], offHand: [12602, 'shieldGreaterStamina'] },
    ],
    races: { 'horde-orc': [0, 1], 'horde-undead': [0, 1], 'horde-tauren': [0, 1], 'horde-troll': [0, 1], 'horde-skyborne-windshaper': [0, 1], 'alliance-human': [2, 3], 'alliance-dwarf': [2, 3], 'alliance-night-elf': [2, 3], 'alliance-gnome': [2, 3], 'alliance-skyborne-high-order': [2, 3] },
  },
  'druid-feral-cat': {
    race: 'horde-tauren',
    talents: '050022-5520002123032213051-05',
    sets: [
      { head: [8345, 'arcanumVoracityAgility'], neck: [15411], shoulder: [12927], back: [13340, 'cloakAgility'], chest: [14637, 'chestGreaterStats'], wrist: [12966, 'bracerSuperiorAgility'], hands: [15063, 'gloveGreaterAgility'], waist: [13252], legs: [15062, 'arcanumVoracityAgility'], feet: [12553, 'bootsGreaterAgility'], finger1: [19325], finger2: [18500], trinket1: [18537], trinket2: [11815], mainHand: [9449, 'twoHandAgility'], ranged: [23198] },
    ],
    races: { 'horde-tauren': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-night-elf': [0, 0], 'alliance-skyborne-high-order': [0, 0] },
  },
  'druid-feral-bear': {
    race: 'horde-tauren',
    talents: '050022-5520032023132210551-',
    sets: [
      { head: [22005, 'arcanumVoracityAgility'], neck: [19491], shoulder: [23254], back: [20691, 'cloakAgility'], chest: [12757, 'chestGreaterStats'], wrist: [19587, 'bracerSuperiorAgility'], hands: [19049, 'gloveThreat'], waist: [20190], legs: [22878, 'arcanumVoracityAgility'], feet: [20715, 'bootsGreaterAgility'], finger1: [13098], finger2: [19325], trinket1: [21180], trinket2: [11815], mainHand: [9449, 'twoHandAgility'], ranged: [23198] },
      { head: [13404, 'arcanumVoracityAgility'], neck: [13177], shoulder: [10783], back: [16342, 'cloakAgility'], chest: [12757, 'chestGreaterStats'], wrist: [12966, 'bracerSuperiorAgility'], hands: [13258, 'gloveThreat'], waist: [14502], legs: [11821, 'arcanumVoracityAgility'], feet: [18716, 'bootsGreaterAgility'], finger1: [19325], finger2: [15855], trinket1: [11811], trinket2: [13966], mainHand: [943, 'twoHandAgility'], ranged: [23198] },
      { head: [22005, 'arcanumVoracityAgility'], neck: [19491], shoulder: [23309], back: [20691, 'cloakAgility'], chest: [12757, 'chestGreaterStats'], wrist: [19587, 'bracerSuperiorAgility'], hands: [19049, 'gloveThreat'], waist: [20045], legs: [23295, 'arcanumVoracityAgility'], feet: [20715, 'bootsGreaterAgility'], finger1: [13098], finger2: [19325], trinket1: [21180], trinket2: [11815], mainHand: [9449, 'twoHandAgility'], ranged: [23198] },
      { head: [13404, 'arcanumVoracityAgility'], neck: [13177], shoulder: [10783], back: [18461, 'cloakAgility'], chest: [12757, 'chestGreaterStats'], wrist: [12966, 'bracerSuperiorAgility'], hands: [13258, 'gloveThreat'], waist: [14502], legs: [11821, 'arcanumVoracityAgility'], feet: [18716, 'bootsGreaterAgility'], finger1: [19325], finger2: [15855], trinket1: [11811], trinket2: [13966], mainHand: [943, 'twoHandAgility'], ranged: [23198] },
    ],
    races: { 'horde-tauren': [0, 1], 'horde-skyborne-windshaper': [0, 1], 'alliance-night-elf': [2, 3], 'alliance-skyborne-high-order': [2, 3] },
  },
  'druid-balance': {
    race: 'horde-tauren',
    talents: '5532220115501351-05-',
    sets: [
      { head: [22267], neck: [22403], shoulder: [20686], back: [11623], chest: [19682, 'chestGreaterStats'], wrist: [21186], hands: [13253], waist: [11662], legs: [19683], feet: [19684], finger1: [20682], finger2: [22339], trinket1: [12930], trinket2: [13968], mainHand: [20214], offHand: [19308] },
      { head: [22267], neck: [22403], shoulder: [20686], back: [11623], chest: [19682, 'chestGreaterStats'], wrist: [21186], hands: [13253], waist: [11662], legs: [19683], feet: [19684], finger1: [20682], finger2: [22339], trinket1: [12930], trinket2: [13968], mainHand: [20070], offHand: [19308] },
    ],
    races: { 'horde-tauren': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-night-elf': [1, 1], 'alliance-skyborne-high-order': [1, 1] },
  },
  'paladin-retribution': {
    race: 'alliance-human',
    talents: '250003-503-052052310012330321',
    sets: [
      { head: [12640, 'arcanumVoracityStrength'], neck: [15411, 'neckStrength'], shoulder: [12927], back: [13340, 'cloakAgility'], chest: [11726, 'chestGreaterStats'], wrist: [12936, 'bracerSuperiorStrength'], hands: [15063, 'gloveGreaterStrength'], waist: [13142], legs: [15062, 'arcanumVoracityStrength'], feet: [14616, 'bootsGreaterAgility'], finger1: [19325], finger2: [18500], trinket1: [11815], trinket2: [13965], mainHand: [12592, 'crusader'], ranged: [22401] },
    ],
    races: { 'horde-undead': [0, 0], 'alliance-human': [0, 0], 'alliance-dwarf': [0, 0] },
  },
  'paladin-protection': {
    race: 'alliance-human',
    talents: '-0530513321301551-50215',
    sets: [
      { head: [12640, 'arcanumFocus'], neck: [19426], shoulder: [274233], back: [20697, 'cloakSuperiorDefense'], chest: [13168, 'chestGreaterStats'], wrist: [12936, 'bracerSuperiorStamina'], hands: [14622, 'gloveThreat'], waist: [22086], legs: [274232, 'arcanumFocus'], feet: [274226, 'bootsGreaterAgility'], finger1: [20682], finger2: [19325], trinket1: [272438], trinket2: [12930], mainHand: [871, 'weaponSpellPower'], offHand: [22336, 'shieldGreaterStamina'] },
      { head: [12620, 'arcanumFocus'], neck: [13091], shoulder: [14552], back: [11930, 'cloakSuperiorDefense'], chest: [14624, 'chestGreaterStats'], wrist: [13951, 'bracerSuperiorStamina'], hands: [14622, 'gloveThreat'], waist: [14620], legs: [14623, 'arcanumFocus'], feet: [14621, 'bootsGreaterAgility'], finger1: [11669], finger2: [15855], trinket1: [11810], trinket2: [4130], mainHand: [871, 'weaponSpellPower'], offHand: [12602, 'shieldGreaterStamina'] },
      { head: [12640, 'arcanumFocus'], neck: [19426], shoulder: [23277], back: [20697, 'cloakSuperiorDefense'], chest: [23272, 'chestGreaterStats'], wrist: [12936, 'bracerSuperiorStamina'], hands: [14622, 'gloveThreat'], waist: [22086], legs: [23273, 'arcanumFocus'], feet: [23275, 'bootsGreaterAgility'], finger1: [20682], finger2: [19325], trinket1: [272438], trinket2: [12930], mainHand: [871, 'weaponSpellPower'], offHand: [22336, 'shieldGreaterStamina'] },
    ],
    races: { 'horde-undead': [0, 1], 'alliance-human': [2, 1], 'alliance-dwarf': [2, 1] },
  },
  'shaman-enhancement': {
    race: 'horde-orc',
    talents: '050003-055030031005102251-05005',
    sets: [
      { head: [13359, 'arcanumVoracityStrength'], neck: [19491, 'neckStrength'], shoulder: [20680], back: [20068, 'cloakAgility'], chest: [11726, 'chestGreaterStats'], wrist: [19587, 'bracerSuperiorStrength'], hands: [19157, 'gloveGreaterStrength'], waist: [13252], legs: [22673, 'arcanumVoracityStrength'], feet: [14616, 'bootsGreaterAgility'], finger1: [19325], finger2: [21182], trinket1: [21180], trinket2: [13965], mainHand: [19323, 'crusader'], ranged: [22395] },
      { head: [13359, 'arcanumVoracityStrength'], neck: [19491, 'neckStrength'], shoulder: [20680], back: [13340, 'cloakAgility'], chest: [11726, 'chestGreaterStats'], wrist: [19587, 'bracerSuperiorStrength'], hands: [19157, 'gloveGreaterStrength'], waist: [13252], legs: [22748, 'arcanumVoracityStrength'], feet: [14616, 'bootsGreaterAgility'], finger1: [19325], finger2: [21182], trinket1: [21180], trinket2: [13965], mainHand: [19323, 'crusader'], ranged: [22395] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-tauren': [0, 0], 'horde-troll': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-dwarf': [1, 1] },
  },
  'shaman-elemental': {
    race: 'horde-orc',
    talents: '5504301500103031-04-053250000001',
    sets: [
      { head: [22267], neck: [19426], shoulder: [23260], back: [20697], chest: [19682, 'chestGreaterStats'], wrist: [21186], hands: [22867], waist: [18676], legs: [19683], feet: [19684], finger1: [22339], finger2: [21190], trinket1: [13968], trinket2: [12930], mainHand: [20214], offHand: [22329], ranged: [23199] },
      { head: [22267], neck: [19426], shoulder: [20680], back: [20697], chest: [19682, 'chestGreaterStats'], wrist: [21186], hands: [21178], waist: [18676], legs: [19683], feet: [19684], finger1: [22339], finger2: [21190], trinket1: [13968], trinket2: [12930], mainHand: [13964], offHand: [22329], ranged: [23199] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-tauren': [0, 0], 'horde-troll': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-dwarf': [1, 1] },
  },
  'rogue-combat': {
    race: 'alliance-human',
    talents: '005303105001-32502300001515231-',
    sets: [
      { head: [22005, 'arcanumVoracityAgility'], neck: [15411, 'neckAgility'], shoulder: [22008], back: [13340, 'cloakAgility'], chest: [22009, 'chestGreaterStats'], wrist: [22004, 'bracerSuperiorAgility'], hands: [22006, 'gloveGreaterAgility'], waist: [22002], legs: [22007, 'arcanumVoracityAgility'], feet: [22003, 'bootsGreaterAgility'], ranged: [18323], finger1: [18500], finger2: [17713], trinket1: [11815], trinket2: [13965], mainHand: [12940, 'crusader'], offHand: [12939, 'crusader'] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-troll': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-human': [0, 0], 'alliance-dwarf': [0, 0], 'alliance-night-elf': [0, 0], 'alliance-gnome': [0, 0], 'alliance-skyborne-high-order': [0, 0] },
  },
  'rogue-assassination': {
    race: 'alliance-human',
    talents: '00531310551521051-302303-002',
    sets: [
      { head: [22005, 'arcanumVoracityAgility'], neck: [15411, 'neckAgility'], shoulder: [22008], back: [13340, 'cloakAgility'], chest: [22009, 'chestGreaterStats'], wrist: [22004, 'bracerSuperiorAgility'], hands: [22006, 'gloveGreaterAgility'], waist: [22002], legs: [22007, 'arcanumVoracityAgility'], feet: [22003, 'bootsGreaterAgility'], ranged: [18323], finger1: [18500], finger2: [17713], trinket1: [11815], trinket2: [13965], mainHand: [12590, 'crusader'], offHand: [14555, 'crusader'] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-troll': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-human': [0, 0], 'alliance-dwarf': [0, 0], 'alliance-night-elf': [0, 0], 'alliance-gnome': [0, 0], 'alliance-skyborne-high-order': [0, 0] },
  },
  'rogue-subtlety': {
    race: 'alliance-human',
    talents: '005303103--0322003311213211551',
    sets: [
      { head: [22005, 'arcanumVoracityAgility'], neck: [15411, 'neckAgility'], shoulder: [22008], back: [13340, 'cloakAgility'], chest: [22009, 'chestGreaterStats'], wrist: [22004, 'bracerSuperiorAgility'], hands: [22006, 'gloveGreaterAgility'], waist: [22002], legs: [22007, 'arcanumVoracityAgility'], feet: [22003, 'bootsGreaterAgility'], ranged: [18323], finger1: [18500], finger2: [17713], trinket1: [11815], trinket2: [13965], mainHand: [12590, 'crusader'], offHand: [14555, 'crusader'] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-troll': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-human': [0, 0], 'alliance-dwarf': [0, 0], 'alliance-night-elf': [0, 0], 'alliance-gnome': [0, 0], 'alliance-skyborne-high-order': [0, 0] },
  },
  'mage-fire': {
    race: 'horde-troll',
    talents: '230225-23550000130133051-005',
    sets: [
      { head: [22267], neck: [22403], shoulder: [23264], back: [20697], chest: [19682, 'chestGreaterStats'], wrist: [21186], hands: [22870], waist: [11662], legs: [19683], feet: [19684], ranged: [11748], finger1: [22339], finger2: [21190], trinket1: [12930], trinket2: [22268], mainHand: [20214], offHand: [19311] },
      { head: [22267], neck: [22403], shoulder: [23319], back: [20697], chest: [19682, 'chestGreaterStats'], wrist: [21186], hands: [23290], waist: [11662], legs: [19683], feet: [19684], ranged: [11748], finger1: [22339], finger2: [21190], trinket1: [12930], trinket2: [22268], mainHand: [20720], offHand: [19311] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-troll': [0, 0], 'alliance-human': [1, 1], 'alliance-gnome': [1, 1], 'alliance-skyborne-high-order': [1, 1] },
  },
  'mage-frost': {
    race: 'horde-troll',
    talents: '230225200100301--055510033002000105',
    sets: [
      { head: [23263], neck: [19426], shoulder: [11782], back: [18350], chest: [14152, 'chestGreaterStats'], wrist: [21186], hands: [13253], waist: [11662], legs: [22883], feet: [22860], ranged: [19108], finger1: [22339], finger2: [22433], trinket1: [12930], trinket2: [13968], mainHand: [13964], offHand: [19315] },
      { head: [23318], neck: [19426], shoulder: [11782], back: [18350], chest: [14152, 'chestGreaterStats'], wrist: [21186], hands: [13253], waist: [11662], legs: [23304], feet: [23291], ranged: [19108], finger1: [22339], finger2: [22433], trinket1: [12930], trinket2: [13968], mainHand: [20070], offHand: [19315] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-troll': [0, 0], 'alliance-human': [1, 1], 'alliance-gnome': [1, 1], 'alliance-skyborne-high-order': [1, 1] },
  },
  'mage-arcane': {
    race: 'horde-troll',
    talents: '050225003100301531-2355001010003-',
    sets: [
      { head: [23263], neck: [19426], shoulder: [11782], back: [18350], chest: [14152, 'chestGreaterStats'], wrist: [21186], hands: [13253], waist: [11662], legs: [22883], feet: [22860], ranged: [19108], finger1: [22339], finger2: [22433], trinket1: [12930], trinket2: [13968], mainHand: [13964], offHand: [19315] },
      { head: [23318], neck: [19426], shoulder: [11782], back: [18350], chest: [14152, 'chestGreaterStats'], wrist: [21186], hands: [13253], waist: [11662], legs: [23304], feet: [23291], ranged: [19108], finger1: [22339], finger2: [22433], trinket1: [12930], trinket2: [13968], mainHand: [20070], offHand: [19315] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-troll': [0, 0], 'alliance-human': [1, 1], 'alliance-gnome': [1, 1], 'alliance-skyborne-high-order': [1, 1] },
  },
  'warlock-destruction': {
    race: 'horde-orc',
    talents: '25-0050203001-0050355103101351',
    sets: [
      { head: [22074, 'arcanumFocus'], neck: [12103], shoulder: [23256], back: [18350], chest: [14153, 'chestGreaterStats'], wrist: [18497], hands: [22077, 'gloveMinorHaste'], waist: [11662], legs: [13170, 'arcanumFocus'], feet: [18735], ranged: [13396], finger1: [12543], finger2: [12545], trinket1: [12930], trinket2: [13968], mainHand: [18372, 'weaponSpellPower'], offHand: [19315] },
      { head: [22074, 'arcanumFocus'], neck: [12103], shoulder: [23311], back: [18350], chest: [14153, 'chestGreaterStats'], wrist: [18497], hands: [22077, 'gloveMinorHaste'], waist: [11662], legs: [13170, 'arcanumFocus'], feet: [18735], ranged: [13396], finger1: [12543], finger2: [12545], trinket1: [12930], trinket2: [13968], mainHand: [18372, 'weaponSpellPower'], offHand: [19315] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-troll': [0, 0], 'alliance-human': [1, 1], 'alliance-gnome': [1, 1] },
  },
  'warlock-affliction': {
    race: 'horde-orc',
    talents: '2555002003520105-0050203001-005',
    sets: [
      { head: [22074, 'arcanumFocus'], neck: [12103], shoulder: [23256], back: [18350], chest: [14153, 'chestGreaterStats'], wrist: [18497], hands: [22077, 'gloveMinorHaste'], waist: [11662], legs: [13170, 'arcanumFocus'], feet: [18735], ranged: [13396], finger1: [12543], finger2: [12545], trinket1: [12930], trinket2: [13968], mainHand: [18372, 'weaponSpellPower'], offHand: [19315] },
      { head: [22074, 'arcanumFocus'], neck: [12103], shoulder: [23311], back: [18350], chest: [14153, 'chestGreaterStats'], wrist: [18497], hands: [22077, 'gloveMinorHaste'], waist: [11662], legs: [13170, 'arcanumFocus'], feet: [18735], ranged: [13396], finger1: [12543], finger2: [12545], trinket1: [12930], trinket2: [13968], mainHand: [18372, 'weaponSpellPower'], offHand: [19315] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-troll': [0, 0], 'alliance-human': [1, 1], 'alliance-gnome': [1, 1] },
  },
  'warlock-demonology': {
    race: 'horde-orc',
    talents: '-0325003221120001351-0450305003',
    sets: [
      { head: [22074, 'arcanumFocus'], neck: [12103], shoulder: [23256], back: [18350], chest: [14153, 'chestGreaterStats'], wrist: [18497], hands: [22077, 'gloveMinorHaste'], waist: [11662], legs: [13170, 'arcanumFocus'], feet: [18735], ranged: [13396], finger1: [12543], finger2: [12545], trinket1: [12930], trinket2: [13968], mainHand: [18372, 'weaponSpellPower'], offHand: [19315] },
      { head: [22074, 'arcanumFocus'], neck: [12103], shoulder: [23311], back: [18350], chest: [14153, 'chestGreaterStats'], wrist: [18497], hands: [22077, 'gloveMinorHaste'], waist: [11662], legs: [13170, 'arcanumFocus'], feet: [18735], ranged: [13396], finger1: [12543], finger2: [12545], trinket1: [12930], trinket2: [13968], mainHand: [18372, 'weaponSpellPower'], offHand: [19315] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-undead': [0, 0], 'horde-troll': [0, 0], 'alliance-human': [1, 1], 'alliance-gnome': [1, 1] },
  },
  'priest-shadow': {
    race: 'horde-troll',
    talents: '025300031303--500320501201312051',
    sets: [
      { head: [22267], neck: [18691], shoulder: [14112], back: [18350], chest: [19682, 'chestGreaterStats'], wrist: [18497], hands: [18407, 'gloveMinorHaste'], waist: [11662], legs: [19683], feet: [19684], ranged: [13396], finger1: [22339], finger2: [12543], trinket1: [12930], trinket2: [13968], mainHand: [13349], offHand: [11904] },
    ],
    races: { 'horde-undead': [0, 0], 'horde-troll': [0, 0], 'alliance-human': [0, 0], 'alliance-dwarf': [0, 0], 'alliance-night-elf': [0, 0], 'alliance-gnome': [0, 0] },
  },
  'hunter-marksmanship': {
    race: 'horde-orc',
    talents: '55-0053552511503051-',
    sets: [
      { head: [18421, 'arcanumVoracityAgility'], neck: [15411, 'neckAgility'], shoulder: [12927], back: [13340, 'cloakAgility'], chest: [11726, 'chestGreaterStats'], wrist: [18375, 'bracerSuperiorAgility'], hands: [15063, 'gloveGreaterAgility'], waist: [18393], legs: [15062, 'arcanumVoracityAgility'], feet: [18506, 'bootsGreaterAgility'], ranged: [2099], finger1: [18500], finger2: [19325], trinket1: [18473], trinket2: [13965], mainHand: [12940], offHand: [12939], ammo: [15997], quiver: [19320] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-tauren': [0, 0], 'horde-troll': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-human': [0, 0], 'alliance-dwarf': [0, 0], 'alliance-night-elf': [0, 0], 'alliance-skyborne-high-order': [0, 0] },
  },
  'hunter-beast-mastery': {
    race: 'horde-orc',
    talents: '5023001505011251-00505505-',
    sets: [
      { head: [18421, 'arcanumVoracityAgility'], neck: [15411, 'neckAgility'], shoulder: [12927], back: [13340, 'cloakAgility'], chest: [11726, 'chestGreaterStats'], wrist: [18375, 'bracerSuperiorAgility'], hands: [15063, 'gloveGreaterAgility'], waist: [18393], legs: [15062, 'arcanumVoracityAgility'], feet: [18506, 'bootsGreaterAgility'], ranged: [2099], finger1: [18500], finger2: [19325], trinket1: [18473], trinket2: [13965], mainHand: [12940], offHand: [12939], ammo: [15997], quiver: [19320] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-tauren': [0, 0], 'horde-troll': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-human': [0, 0], 'alliance-dwarf': [0, 0], 'alliance-night-elf': [0, 0], 'alliance-skyborne-high-order': [0, 0] },
  },
  'hunter-survival': {
    race: 'horde-orc',
    talents: '-00505515-55005003124000005',
    sets: [
      { head: [18421, 'arcanumVoracityAgility'], neck: [15411, 'neckAgility'], shoulder: [12927], back: [13340, 'cloakAgility'], chest: [11726, 'chestGreaterStats'], wrist: [18375, 'bracerSuperiorAgility'], hands: [15063, 'gloveGreaterAgility'], waist: [18393], legs: [15062, 'arcanumVoracityAgility'], feet: [18506, 'bootsGreaterAgility'], ranged: [2099], finger1: [18500], finger2: [19325], trinket1: [18473], trinket2: [13965], mainHand: [12940], offHand: [12939], ammo: [15997], quiver: [19320] },
    ],
    races: { 'horde-orc': [0, 0], 'horde-tauren': [0, 0], 'horde-troll': [0, 0], 'horde-skyborne-windshaper': [0, 0], 'alliance-human': [0, 0], 'alliance-dwarf': [0, 0], 'alliance-night-elf': [0, 0], 'alliance-skyborne-high-order': [0, 0] },
  },
}
