// The optimizer's public API (docs/optimizer.md, decision D30): what the CLI
// (scripts/tune/optimize.mjs) and the app's Optimize flow use.
export { ENGINES_PER_LANE, EngineCache, type FightRunner, type FightSamples, localFightRunner, type PlanSource, planKey, runFights, SearchTooLargeError } from './fights'
export {
  type Bound,
  type Constraint,
  CRIT_IMMUNE,
  CRUSH_IMMUNE,
  constraintName,
  defaultConstraints,
  EHP_FLOOR,
  effectiveHealth,
  formatConstraint,
  immunityTables,
  limits,
  meetsSheet,
  parseConstraint,
  SHEET_STATS,
  type SheetStat,
  sheetValues,
  type SheetValues,
} from './constraints'
export {
  defaultGoal,
  ELIMINATION_TAIL,
  eliminationZ,
  type Goal,
  GOALS,
  type Interval,
  lower,
  meanInterval,
  normalQuantile,
  pairedInterval,
  type Score,
  scoredGoal,
  scoreReads,
  scorer,
  tieBreaker,
  tQuantile,
  tTail,
  upper,
  Z99,
} from './objective'
export {
  applyCandidate,
  type AssumptionChanges,
  assumptionChanges,
  BUDGETS,
  type Budget,
  type BudgetId,
  type Candidate,
  candidateKey,
  candidatePlan,
  confirm,
  confirmFights,
  type Confirmation,
  type Estimate,
  type Excluded,
  type FittedBudget,
  FIRST_ROUND_MIN,
  firstRound,
  fitBudget,
  gearKey,
  isSetup,
  MAX_SEARCH_FIGHTS,
  MIN_CONFIRM_FIGHTS,
  MIN_FIRST_ROUND,
  type Narrowed,
  optimize,
  optimizeInTurns,
  type OptimizeOptions,
  type OptimizeProgress,
  type OptimizeReport,
  setupCandidate,
  TANK_TREE,
  TANK_TREE_POINTS,
  TURNS_RESERVE,
  talentConstraintsOf,
  type TalentSearch,
} from './optimize'
export { race, type RaceOptions, type RaceProgress, type RaceResult, type RaceStatus, type RoundLog, type Standing } from './race'
export { screenTalents, type TalentScreen, type TalentVerdict } from './screen'
export { type TalentBuild, type TalentConstraints, type TalentRole, MAX_BUILDS, talentSpace, talentSpaceSize, type TalentSpace } from './talents'
export { describeBuildChange, describeGearChange } from './describe'
export { type ContentOf, type GearContent, itemContent, LATER_RAID_ITEMS, LATER_RAID_SETS, ONYXIA_ITEMS, PRE_RAID_MAX_ITEM_LEVEL } from './content'
export {
  appliedBonus,
  bestEnchant,
  contentOf,
  describeSource,
  enchantFits,
  enchantsFor,
  ENCHANTS_PER_ITEM,
  GEAR_GROUPS,
  GEAR_SOURCES,
  type Gear,
  type GearContext,
  gearContext,
  type GearFilters,
  type GearGroup,
  gearProblems,
  type GearSource,
  greedyGear,
  groupGears,
  GROUP_SLOTS,
  hasUnmeasuredRating,
  itemSource,
  PER_SLOT,
  POOL,
  type Rankings,
  SEARCHED_SLOTS,
  SHIELD_SPECS,
  slotPool,
  type StatWeights,
  UNCONFIRMED_ENCHANTS,
  UNMEASURED_STATS,
  unmeasuredChanges,
  weighedItem,
} from './gear'
export {
  chooseStep,
  FINAL_SHARE,
  GEAR_PASSES,
  type GearProgress,
  type GearReport,
  type GearSearchOptions,
  type GearStart,
  type GearStep,
  gearPools,
  MEASURE_FIGHTS,
  measureStatWeights,
  MIN_RANK_FIGHTS,
  optimizeGear,
  optimizeTogether,
  type PassKind,
  perturbPlan,
  rankGear,
  rankingPlans,
  RANK_SHARE,
  runPlans,
  survivalReference,
  type TogetherPass,
  UNMEASURED_MARGIN,
  WEIGHT_FIGHTS,
  type WeightsMeasured,
} from './gear-search'
