// The optimizer's public API (docs/optimizer.md, decision D30): what the CLI
// (scripts/tune/optimize.mjs) and the app's Optimize flow use.
export { ENGINES_PER_LANE, EngineCache, type FightRunner, type FightSamples, localFightRunner, type PlanSource, planKey, runFights, SearchTooLargeError } from './fights'
export {
  type Bound,
  type Constraint,
  CRIT_IMMUNE,
  CRUSH_IMMUNE,
  constraintName,
  defaultConstraints,
  EHP_FLOOR,
  effectiveHealth,
  formatConstraint,
  immunityTables,
  limits,
  meetsSheet,
  parseConstraint,
  SHEET_STATS,
  type SheetStat,
  sheetValues,
  type SheetValues,
} from './constraints'
export {
  defaultGoal,
  ELIMINATION_TAIL,
  eliminationZ,
  type Goal,
  GOALS,
  type Interval,
  lower,
  meanInterval,
  normalQuantile,
  pairedInterval,
  type Score,
  scoredGoal,
  scoreReads,
  scorer,
  tieBreaker,
  tQuantile,
  tTail,
  upper,
  Z99,
} from './objective'
export {
  applyCandidate,
  type AssumptionChanges,
  assumptionChanges,
  BUDGETS,
  type Budget,
  type BudgetId,
  type Candidate,
  candidatePlan,
  confirm,
  type Confirmation,
  type Estimate,
  type Excluded,
  type FittedBudget,
  FIRST_ROUND_MIN,
  firstRound,
  fitBudget,
  isSetup,
  MAX_SEARCH_FIGHTS,
  MIN_FIRST_ROUND,
  type Narrowed,
  optimize,
  optimizeInTurns,
  type OptimizeOptions,
  type OptimizeProgress,
  type OptimizeReport,
  setupCandidate,
  TANK_TREE,
  TANK_TREE_POINTS,
  talentConstraintsOf,
  type TalentSearch,
} from './optimize'
export { race, type RaceOptions, type RaceProgress, type RaceResult, type RaceStatus, type RoundLog, type Standing } from './race'
export { screenTalents, type TalentScreen, type TalentVerdict } from './screen'
export { type TalentBuild, type TalentConstraints, type TalentRole, MAX_BUILDS, talentSpace, talentSpaceSize, type TalentSpace } from './talents'
export { describeBuildChange } from './describe'
