// Unit tests for the client item derivation (scripts/scrape/lib/item-stats.mjs), built from
// real rows of the Forever 1.60.1.69913 and Classic Era 1.15.9.69722 clients. The fixture is
// generated by `node scripts/scrape/items-client.mjs --fixtures`.
// Expected values are the items' in-game tooltips (as foreverchanges.pro recorded them; the last
// such dataset is `git show b94a076:src/data/items/pre-bis.json`), and the worked examples in
// docs/data/client.md#items-from-the-client.
import { describe, expect, it } from "vitest";
import fixture from "./__fixtures__/item-stats.json";
import { AURA_STAT, NOT_STAT_AURAS, baseArmor, casterWeapon, casterWeaponProblem, createFallbackContext, createItemContext, deriveItem, deriveSet, statAmount, statBudget, statEquip } from "./item-stats.mjs";

const forever = createItemContext(fixture.forever.tables, fixture.forever.gameTables);
const classic = createItemContext(fixture.classic.tables, fixture.classic.gameTables);
const row = (ctx, id) => ctx.sparse.get(id);

describe("Forever budget allocations (docs/data/client.md#stat-budget)", () => {
  it("Lionheart Helm: budget 45 (Epic, item level 61, head) and round(allocation × 45 / 10000)", () => {
    const r = row(forever, 12640);
    expect(statBudget(forever, r)).toBe(45);
    expect(r.StatPercentEditor.slice(0, 3)).toEqual([4000, 6222, 4444]);
    expect([0, 1, 2].map((i) => statAmount(forever, r, i))).toEqual([18, 28, 20]); // 18.0, 27.999, 19.998
    const item = deriveItem(forever, 12640);
    expect(item.layout).toBe("budget");
    expect(item.stats).toEqual({ strength: 18, critRating: 28, hitRating: 20, armor: 565 });
  });

  it("Lionheart Helm armor: round(Qualitymod[Epic] 1.2 × plate total 3619.31 × head 0.13) = 565", () => {
    expect(baseArmor(forever, row(forever, 12640), forever.item.get(12640))).toBe(565);
  });
});

describe("Classic Era stored amounts and equip spells", () => {
  it("Lionheart Helm: +18 Strength stored, 2% crit and 2% hit from equip spells 7598 and 15465", () => {
    const item = deriveItem(classic, 12640);
    expect(item.layout).toBe("amounts");
    expect(item.stats).toEqual({ strength: 18, armor: 565, crit: 2, hit: 2 });
  });

  it("Hand of Justice (no Forever data): +20 Attack Power, and its extra-attack proc stays an effect", () => {
    const item = deriveItem(classic, 11815);
    expect(item.stats).toEqual({ attackPower: 20 });
    expect(item.effects).toEqual([expect.objectContaining({ kind: "proc", trigger: "equip", spellId: 15600 })]);
    expect(deriveItem(forever, 11815)).toBeNull();
  });

  it("Devilsaur Leggings: 46 melee and 48 ranged AP read as +46 Attack Power plus 2 ranged", () => {
    expect(deriveItem(classic, 15062).stats).toEqual({ stamina: 12, armor: 148, attackPower: 46, rangedAttackPower: 2, crit: 1 });
  });
});

describe("weapons (docs/data/client.md#weapon-damage)", () => {
  it("one-hand: Annihilator 69–129, speed 2.4, 41.3 DPS, and its chance-on-hit spell", () => {
    const item = deriveItem(forever, 12798);
    expect(item.weapon).toMatchObject({ min: 69, max: 129, speed: 2.4, dps: 41.3, school: "Physical", skill: "Axes" });
    expect(item.stats).toEqual({ attackPower: 14 });
    expect(item.effects).toEqual([expect.objectContaining({ kind: "proc", trigger: "chanceOnHit", spellId: 16928 })]);
  });

  it("two-hand: Arcanite Reaper 153–256, speed 3.8, 53.8 DPS", () => {
    const item = deriveItem(forever, 12784);
    expect(item.weapon).toMatchObject({ min: 153, max: 256, speed: 3.8, dps: 53.8, skill: "Two-Handed Axes" });
    expect(item.stats).toEqual({ stamina: 13, attackPower: 62 });
  });

  it("caster weapons trade DPS for spell power worth 2 × the group-0 budget", () => {
    const whiteout = deriveItem(forever, 19101);
    expect(whiteout.weapon).toMatchObject({ min: 102, max: 154, dps: 41.3 });
    expect(whiteout.stats).toEqual({ intellect: 16, stamina: 25, spellPower: 74 });
    // Crackling Staff: the same DPS cut, but it keeps the spell power its stats give.
    const crackling = deriveItem(forever, 19102);
    expect(crackling.weapon).toMatchObject({ min: 102, max: 154, dps: 41.3 });
    expect(crackling.stats).toEqual({ intellect: 25, spellPower: 25 });
  });

  it("an Epic caster weapon takes its Classic Era item's spell power and no DPS cut (Mindfang +30, not the extrapolated +94)", () => {
    const linked = { ...forever, classic };
    const mindfang = deriveItem(linked, 20214);
    expect(mindfang.stats.spellPower).toBe(30);
    expect(deriveItem(classic, 20214).stats.spellPower).toBe(30);
    // No cut: the ItemDamageOneHand value as is (47.4 DPS; Classic Era stores 56–105 too).
    expect(mindfang.weapon).toMatchObject({ min: 56, max: 105, dps: 47.4, dpsSource: "ItemDamageOneHand" });
    // Without a linked Classic Era context there's nothing to take: no spell power.
    expect(deriveItem(forever, 20214).stats.spellPower).toBeUndefined();
    // The item says which stats came from Classic Era (the results' assumption reads it); a Rare doesn't.
    expect(mindfang.classicStats).toEqual(["spellPower"]);
    expect(deriveItem(linked, 19101).classicStats).toBeUndefined();
    expect(casterWeaponProblem(linked, row(forever, 20214))).toBeNull();
  });

  it("a caster weapon off the fitted quality with nothing to take is a problem the scraper fails on (both paths)", () => {
    const mindfang = row(forever, 20214);
    // No Classic Era item at all.
    const noClassic = { ...forever, classic: { ...classic, sparse: new Map() } };
    expect(casterWeaponProblem(noClassic, mindfang)).toBe("it has no Classic Era item to take spell power from");
    // A Classic Era item with no spell stat: Lionheart Helm's row under Mindfang's id.
    const helm = { ...row(classic, 12640), ID: 20214 };
    const noSpellStats = { ...forever, classic: { ...classic, sparse: new Map([[20214, helm]]), itemEffects: new Map() } };
    expect(casterWeapon(noSpellStats, mindfang)).toMatchObject({ fromClassic: true, hasClassic: true, stats: [] });
    expect(casterWeaponProblem(noSpellStats, mindfang)).toBe("its Classic Era item carries no spell power, healing or spell damage to take");
    // A weapon with spell stats of its own takes none and needs none (Crackling Staff's +25, were it Epic).
    const crackling = { ...row(forever, 19102), OverallQualityID: 4 };
    expect(casterWeaponProblem(noClassic, crackling)).toBeNull();
    // Not a caster weapon: never a problem.
    expect(casterWeaponProblem(noClassic, row(forever, 12640))).toBeNull();
  });

  it("the Rare-fitted rule isn't extrapolated to Uncommon either: an Uncommon caster weapon takes the Classic Era path", () => {
    const uncommon = { ...row(forever, 19101), OverallQualityID: 2 };
    const c = casterWeapon({ ...forever, classic }, uncommon);
    expect(c).toMatchObject({ spellPower: 0, fromClassic: true });
    expect(casterWeapon(forever, row(forever, 19101))).toMatchObject({ spellPower: 74, stats: [["spellPower", 74]] });
    expect(casterWeapon(forever, row(forever, 19101)).fromClassic).toBeUndefined();
  });

  it("Classic Era extra damage counts toward DPS; its school is Item.DamageType[1]", () => {
    const item = deriveItem(classic, 13982);
    expect(item.weapon).toMatchObject({ min: 142, max: 214, speed: 3.3, dps: 57.4, extraDamage: [{ min: 1, max: 22, school: "Frost" }] });
  });
});

describe("shields and block value", () => {
  it("Forever shield: ItemArmorShield armor plus stat-50 bonus armor, no innate block value", () => {
    const item = deriveItem(forever, 274418);
    expect(item.stats).toEqual({ stamina: 15, bonusArmor: 82, armor: 1994 }); // tooltip: 2076 Armor
    expect(item.shieldBlockValue).toBeNull();
  });

  it("Classic Era shield: equip block chance and value, and innate block from ShieldBlockRegular", () => {
    const item = deriveItem(classic, 18499);
    expect(item.stats).toEqual({ armor: 2121, block: 2, blockValue: 18 });
    expect(item.shieldBlockValue).toBe(39);
  });
});

describe("equip spells and effects", () => {
  it("Rune of the Guard Captain: +14 AP always; the area-restricted +28 stays a conditional effect", () => {
    const item = deriveItem(forever, 19120);
    expect(item.stats).toEqual({ hitRating: 7, attackPower: 14 });
    expect(item.effects).toEqual([
      expect.objectContaining({ kind: "equip", spellId: 1287704, condition: { requiredAreasId: 9161 }, stats: { attackPower: 28 } }),
    ]);
  });

  it("Stormpike Insignia: a use effect on a 120 s category cooldown", () => {
    const item = deriveItem(forever, 17902);
    expect(item.stats).toEqual({ frostResistance: 8, healthRegen: 18, dodgeRating: 12 });
    expect(item.effects).toEqual([expect.objectContaining({ kind: "use", spellId: 22564, cooldownMs: null, categoryCooldownMs: 120000 })]);
  });
});

describe("sets (ItemSet + ItemSetSpell)", () => {
  it("Champion's Battlegear (Forever): flat stat bonuses become stats, the rest stays a spell", () => {
    const set = deriveSet(forever, 281);
    expect(set.name).toBe("Champion's Battlegear");
    expect(set.itemIds).toHaveLength(6);
    expect(set.bonuses).toEqual([
      expect.objectContaining({ pieces: 2, spellId: 14049, stats: { attackPower: 40 } }),
      expect.objectContaining({ pieces: 4, spellId: 22738, unmapped: [expect.objectContaining({ aura: 107 })] }),
      expect.objectContaining({ pieces: 6, spellId: 14467, stats: { stamina: 20 } }),
    ]);
  });

  it("The Gladiator (Classic Era): +20 armor, +2 defense, +10 AP, 1% crit", () => {
    expect(deriveSet(classic, 1).bonuses.map((b) => [b.pieces, b.stats])).toEqual([
      [2, { bonusArmor: 20 }],
      [3, { defense: 2 }],
      [4, { attackPower: 10 }],
      [5, { crit: 1 }],
    ]);
  });

  // L8: Forever's 5-piece is aura 290 (all crit), which adds to melee, ranged and spell crit.
  it("The Gladiator (Forever): the 5-piece's aura 290 is 1% crit with attacks and spells", () => {
    const five = deriveSet(forever, 1).bonuses.find((b) => b.pieces === 5);
    expect(five).toMatchObject({ spellId: 1314795, stats: { crit: 1, spellCrit: 1 } });
    expect(five.unmapped).toBeUndefined();
  });
});

describe("the aura → stat table (docs/data/client.md#aura--stat)", () => {
  it("maps all crit (290) and Forever's block value (274)", () => {
    expect(AURA_STAT[290](3, 0)).toEqual([["crit", 3], ["spellCrit", 3]]);
    expect(AURA_STAT[274](18, 0)).toEqual([["blockValue", 18]]);
  });

  it("lists an aura as a stat or as not one, never both", () => {
    expect(Object.keys(NOT_STAT_AURAS).filter((a) => a in AURA_STAT)).toEqual([]);
  });
});

// L5: items with no Forever ItemSparse row (decision D6) keep Classic Era's stats, and take their
// effects from the Forever client wherever it has them (docs/data/items.md#effects-of-fallback-items).
describe("fallback items: Classic Era stats, Forever effects", () => {
  const fallback = createFallbackContext(classic, forever);

  it("Seal of the Dawn: its equip spell 23930 is read from Forever (+78 AP against Undead, Classic Era 81)", () => {
    expect(deriveItem(classic, 13209).stats).toEqual({ attackPowerVsUndead: 81 });
    const item = deriveItem(fallback, 13209);
    expect(item.stats).toEqual({ attackPowerVsUndead: 78 });
    expect(item.statSpellIds).toEqual([23930]);
    expect(fallback.spellFrom(23930)).toBe("forever");
    expect(fallback.effectsFrom(13209)).toBe("classic"); // the Forever client links it no item effects
  });

  it("Hand of Justice: the Classic Era +20 AP spell stays (Forever moved it to ItemSparse); the proc is Forever's", () => {
    const item = deriveItem(fallback, 11815);
    expect(item.stats).toEqual({ attackPower: 20 });
    expect(item.statSpellIds).toEqual([9331]);
    expect(item.effects).toEqual([expect.objectContaining({ kind: "proc", trigger: "equip", spellId: 15600 })]);
    expect(fallback.effectsFrom(11815)).toBe("forever");
  });

  it("Blackhand's Breadth: Forever's item effects, +1% crit (1318954) in place of Classic Era's +2% (7598), and its new use", () => {
    expect(deriveItem(classic, 13965).stats).toEqual({ crit: 2 });
    const item = deriveItem(fallback, 13965);
    expect(item.stats).toEqual({ crit: 1 });
    expect(item.statSpellIds).toEqual([1318954]);
    expect(item.effects.map((e) => [e.kind, e.spellId])).toEqual(expect.arrayContaining([["use", 1318944]]));
    expect(fallback.effectsFrom(13965)).toBe("forever");
  });

  it("Diamond Flask: Forever's item effect casts 363881 (CHUG!) with its 6 min cooldown and category 1153", () => {
    expect(deriveItem(classic, 20130).effects).toEqual([expect.objectContaining({ kind: "use", spellId: 363880 })]);
    const item = deriveItem(fallback, 20130);
    expect(item.effects).toEqual(
      expect.arrayContaining([expect.objectContaining({ kind: "use", spellId: 363881, cooldownMs: 360000, categoryCooldownMs: 60000, categoryId: 1153 })]),
    );
  });

  // RL2: Forever re-pointed the Classic Era row's ItemEffect 99949 from 13669 (+1% dodge) to a Use.
  it("Mark of Tyranny: Forever re-points ItemEffect 99949 to a Use (1287842), so Classic Era's +1% dodge (13669) goes", () => {
    expect(classic.itemEffects.get(13966).map((e) => [e.ID, e.SpellID])).toEqual([[99949, 13669]]);
    expect(deriveItem(classic, 13966).statSpellIds).toEqual([13669]);
    const item = deriveItem(fallback, 13966);
    expect(item.stats.dodge).toBeUndefined();
    expect(item.statSpellIds).toEqual([]);
    expect(item.effects.map((e) => [e.kind, e.spellId])).toEqual([["use", 1287842]]);
    expect(fallback.effectsFrom(13966)).toBe("forever");
  });

  it("Barrier Shield: block value comes from Forever's aura 274 (the same 18)", () => {
    const item = deriveItem(fallback, 18499);
    expect(item.stats).toEqual({ armor: 2121, block: 2, blockValue: 18 });
    expect(item.statSpellIds).toEqual([13675, 22912]);
    expect(fallback.spellEffects.get(22912).map((e) => e.EffectAura)).toEqual([274]);
  });

  it("statEquip: an equip spell whose every aura is a stat", () => {
    expect(statEquip(fallback, { TriggerType: 1, SpellID: 23930 })).toBe(true);
    expect(statEquip(fallback, { TriggerType: 1, SpellID: 15600 })).toBe(false); // a proc
    expect(statEquip(fallback, { TriggerType: 0, SpellID: 9331 })).toBe(false); // not an equip
  });
});
