// Unit tests for the client item derivation (scripts/scrape/lib/item-stats.mjs), built from
// real rows of the Forever 1.60.1.69913 and Classic Era 1.15.9.69722 clients. The fixture is
// generated by `node scripts/scrape/items-client.mjs --compare --fixtures`.
// Expected values are the items' tooltips in src/data/items/pre-bis.json, and the worked
// examples in docs/data/client.md#items-from-the-client.
import { describe, expect, it } from "vitest";
import fixture from "./__fixtures__/item-stats.json";
import { createItemContext, deriveItem, deriveSet, statAmount, statBudget, baseArmor } from "./item-stats.mjs";

const forever = createItemContext(fixture.forever.tables, fixture.forever.gameTables);
const classic = createItemContext(fixture.classic.tables, fixture.classic.gameTables);
const row = (ctx, id) => ctx.sparse.get(id);

describe("Forever budget allocations (docs/data/client.md#stat-budget)", () => {
  it("Lionheart Helm: budget 45 (Epic, item level 61, head) and round(allocation × 45 / 10000)", () => {
    const r = row(forever, 12640);
    expect(statBudget(forever, r)).toBe(45);
    expect(r.StatPercentEditor.slice(0, 3)).toEqual([4000, 6222, 4444]);
    expect([0, 1, 2].map((i) => statAmount(forever, r, i))).toEqual([18, 28, 20]); // 18.0, 27.999, 19.998
    const item = deriveItem(forever, 12640);
    expect(item.layout).toBe("budget");
    expect(item.stats).toEqual({ strength: 18, critRating: 28, hitRating: 20, armor: 565 });
  });

  it("Lionheart Helm armor: round(Qualitymod[Epic] 1.2 × plate total 3619.31 × head 0.13) = 565", () => {
    expect(baseArmor(forever, row(forever, 12640), forever.item.get(12640))).toBe(565);
  });
});

describe("Classic Era stored amounts and equip spells", () => {
  it("Lionheart Helm: +18 Strength stored, 2% crit and 2% hit from equip spells 7598 and 15465", () => {
    const item = deriveItem(classic, 12640);
    expect(item.layout).toBe("amounts");
    expect(item.stats).toEqual({ strength: 18, armor: 565, crit: 2, hit: 2 });
  });

  it("Hand of Justice (no Forever data): +20 Attack Power, and its extra-attack proc stays an effect", () => {
    const item = deriveItem(classic, 11815);
    expect(item.stats).toEqual({ attackPower: 20 });
    expect(item.effects).toEqual([expect.objectContaining({ kind: "proc", trigger: "equip", spellId: 15600 })]);
    expect(deriveItem(forever, 11815)).toBeNull();
  });

  it("Devilsaur Leggings: 46 melee and 48 ranged AP read as +46 Attack Power plus 2 ranged", () => {
    expect(deriveItem(classic, 15062).stats).toEqual({ stamina: 12, armor: 148, attackPower: 46, rangedAttackPower: 2, crit: 1 });
  });
});

describe("weapons (docs/data/client.md#weapon-damage)", () => {
  it("one-hand: Annihilator 69–129, speed 2.4, 41.3 DPS, and its chance-on-hit spell", () => {
    const item = deriveItem(forever, 12798);
    expect(item.weapon).toMatchObject({ min: 69, max: 129, speed: 2.4, dps: 41.3, school: "Physical", skill: "Axes" });
    expect(item.stats).toEqual({ attackPower: 14 });
    expect(item.effects).toEqual([expect.objectContaining({ kind: "proc", trigger: "chanceOnHit", spellId: 16928 })]);
  });

  it("two-hand: Arcanite Reaper 153–256, speed 3.8, 53.8 DPS", () => {
    const item = deriveItem(forever, 12784);
    expect(item.weapon).toMatchObject({ min: 153, max: 256, speed: 3.8, dps: 53.8, skill: "Two-Handed Axes" });
    expect(item.stats).toEqual({ stamina: 13, attackPower: 62 });
  });

  it("caster weapons trade DPS for spell power worth 2 × the group-0 budget", () => {
    const whiteout = deriveItem(forever, 19101);
    expect(whiteout.weapon).toMatchObject({ min: 102, max: 154, dps: 41.3 });
    expect(whiteout.stats).toEqual({ intellect: 16, stamina: 25, spellPower: 74 });
    // Crackling Staff: the same DPS cut, but it keeps the spell power its stats give.
    const crackling = deriveItem(forever, 19102);
    expect(crackling.weapon).toMatchObject({ min: 102, max: 154, dps: 41.3 });
    expect(crackling.stats).toEqual({ intellect: 25, spellPower: 25 });
  });

  it("Classic Era extra damage counts toward DPS; its school isn't stored", () => {
    const item = deriveItem(classic, 13982);
    expect(item.weapon).toMatchObject({ min: 142, max: 214, speed: 3.3, dps: 57.4, extraDamage: [{ min: 1, max: 22, school: null }] });
  });
});

describe("shields and block value", () => {
  it("Forever shield: ItemArmorShield armor plus stat-50 bonus armor, no innate block value", () => {
    const item = deriveItem(forever, 274418);
    expect(item.stats).toEqual({ stamina: 15, bonusArmor: 82, armor: 1994 }); // tooltip: 2076 Armor
    expect(item.shieldBlockValue).toBeNull();
  });

  it("Classic Era shield: equip block chance and value, and innate block from ShieldBlockRegular", () => {
    const item = deriveItem(classic, 18499);
    expect(item.stats).toEqual({ armor: 2121, block: 2, blockValue: 18 });
    expect(item.shieldBlockValue).toBe(39);
  });
});

describe("equip spells and effects", () => {
  it("Rune of the Guard Captain: +14 AP always; the area-restricted +28 stays a conditional effect", () => {
    const item = deriveItem(forever, 19120);
    expect(item.stats).toEqual({ hitRating: 7, attackPower: 14 });
    expect(item.effects).toEqual([
      expect.objectContaining({ kind: "equip", spellId: 1287704, condition: { requiredAreasId: 9161 }, stats: { attackPower: 28 } }),
    ]);
  });

  it("Stormpike Insignia: a use effect on a 120 s category cooldown", () => {
    const item = deriveItem(forever, 17902);
    expect(item.stats).toEqual({ frostResistance: 8, healthRegen: 18, dodgeRating: 12 });
    expect(item.effects).toEqual([expect.objectContaining({ kind: "use", spellId: 22564, cooldownMs: null, categoryCooldownMs: 120000 })]);
  });
});

describe("sets (ItemSet + ItemSetSpell)", () => {
  it("Champion's Battlegear (Forever): flat stat bonuses become stats, the rest stays a spell", () => {
    const set = deriveSet(forever, 281);
    expect(set.name).toBe("Champion's Battlegear");
    expect(set.itemIds).toHaveLength(6);
    expect(set.bonuses).toEqual([
      expect.objectContaining({ pieces: 2, spellId: 14049, stats: { attackPower: 40 } }),
      expect.objectContaining({ pieces: 4, spellId: 22738, unmapped: [expect.objectContaining({ aura: 107 })] }),
      expect.objectContaining({ pieces: 6, spellId: 14467, stats: { stamina: 20 } }),
    ]);
  });

  it("The Gladiator (Classic Era): +20 armor, +2 defense, +10 AP, 1% crit", () => {
    expect(deriveSet(classic, 1).bonuses.map((b) => [b.pieces, b.stats])).toEqual([
      [2, { bonusArmor: 20 }],
      [3, { defense: 2 }],
      [4, { attackPower: 10 }],
      [5, { crit: 1 }],
    ]);
  });
});
