// The old (foreverchanges.pro) races dataset against the new (client) one: race ids, names,
// factions, icons and classes, then each race's racials (paired by id, then name) field by field,
// and the Classic racials each race lost. Writes <outDir>/races-diff.md and .json and prints a
// summary. Run through `node scripts/scrape/races-client.mjs --diff` after a write.
// docs/data/races.md#from-foreverchanges-to-the-client records the result.

import fs from "node:fs";
import path from "node:path";

/** Fields the site made up that the client dataset no longer carries. */
const DROPPED = {
  top: ["research"],
  race: ["classAvailabilityStatus", "compatibilityConflicts", "reportedRemovals", "sources"],
  racial: ["displayKind", "evidenceStatus", "comparisonStatus", "discoveredAt", "notes", "sources"],
};

const json = (v) => JSON.stringify(v ?? null, (_k, x) => (x && typeof x === "object" && !Array.isArray(x) ? Object.fromEntries(Object.entries(x).sort(([a], [b]) => a.localeCompare(b))) : x));
const set = (xs) => json([...(xs ?? [])].sort());
const ws = (s) => (s ?? "").replace(/\s+/g, " ").trim();

/** How the site's Classic text relates to the client's: the site prefixed Wowhead's tooltip header. */
function classicTextKind(o, n) {
  if ((o ?? null) === (n ?? null)) return null;
  if (!o || !n) return o ? "dropped" : "added";
  const header = /^((?:Instant|[\d.]+ sec cast|Channeled)(?:, [^.]+ cooldown)?)\. /.exec(o);
  if (header && ws(o.slice(header[0].length)) === ws(n)) return "header prefix moved to classic.tooltip";
  if (header) return "header prefix moved + wording or numbers";
  return "wording or numbers";
}

export function diffRaces({ old, next, outDir, repoRoot }) {
  const report = { top: {}, races: {}, kinds: {} };
  const count = (k) => (report.kinds[k] = (report.kinds[k] ?? 0) + 1);
  const md = ["# Races: foreverchanges.pro snapshot vs client dataset", "", "Generated by `node scripts/scrape/races-client.mjs --diff`. Races are paired by id, racials by id (then name).", ""];

  const top = (field, a, b, kind = field) => {
    if (json(a) !== json(b)) {
      report.top[field] = { kind, old: a, new: b };
      count(kind);
    }
  };
  top("classOrder", old.classOrder, next.classOrder, "class order (now ChrClasses id order)");
  for (const cls of Object.keys(old.simClassAvailability))
    for (const side of ["forever", "classic"]) {
      const a = old.simClassAvailability[cls][side];
      const b = next.simClassAvailability[cls]?.[side];
      if (set(a) !== set(b)) top(`simClassAvailability.${cls}.${side}`, a, b, "sim class availability");
      else if (json(a) !== json(b)) top(`simClassAvailability.${cls}.${side}`, a, b, "sim class availability order");
    }
  const combo = (c) => `${c.raceId}/${c.class}`;
  if (set(old.newCombos.map(combo)) !== set(next.newCombos.map(combo))) top("newCombos", old.newCombos.map(combo), next.newCombos.map(combo), "new race/class pairs");
  else if (json(old.newCombos.map(combo)) !== json(next.newCombos.map(combo))) top("newCombos", old.newCombos.map(combo), next.newCombos.map(combo), "new race/class pairs order");
  const droppedTop = DROPPED.top.filter((f) => f in old && !(f in next));

  const newById = new Map(next.races.map((r) => [r.id, r]));
  for (const o of old.races) {
    const n = newById.get(o.id);
    const changes = [];
    if (!n) {
      count("race removed");
      report.races[o.id] = { removed: true };
      continue;
    }
    const cmp = (field, a, b, kind = field) => {
      if (json(a) !== json(b)) {
        changes.push({ field, kind, old: a ?? null, new: b ?? null });
        count(kind);
      }
    };
    for (const f of ["name", "baseName", "faction", "icon", "newInForever"]) cmp(f, o[f], n[f]);
    for (const f of ["forever", "classic", "addedInForever", "removedInForever"]) {
      if (set(o.classes[f]) !== set(n.classes[f])) cmp(`classes.${f}`, o.classes[f], n.classes[f]);
      else if (json(o.classes[f]) !== json(n.classes[f])) cmp(`classes.${f}`, o.classes[f], n.classes[f], "class list order (now ChrClasses id order)");
    }
    cmp("removals", (o.reportedRemovals ?? []).map((x) => x.name).sort(), n.removedRacials.map((x) => x.name).sort(), "removed racials (reported → client)");
    const oldIds = o.racials.map((x) => x.id);
    const newIds = n.racials.map((x) => x.id);
    if (set(oldIds) === set(newIds) && json(oldIds) !== json(newIds)) cmp("racial order", oldIds, newIds, "racial order (now SkillLineAbility order)");
    for (const or of o.racials) {
      const nr = n.racials.find((x) => x.id === or.id) ?? n.racials.find((x) => x.name === or.name);
      if (!nr) {
        cmp(`racial ${or.name}`, or.id, null, "racial removed");
        continue;
      }
      const f = (field) => `${or.name}: ${field}`;
      cmp(f("id"), or.id, nr.id);
      cmp(f("name"), or.name, nr.name);
      cmp(f("icon"), or.icon, nr.icon);
      cmp(f("passive"), or.passive, nr.passive);
      cmp(f("changeLabel"), or.changeLabel, nr.changeLabel);
      cmp(f("changeKind"), or.changeKind, nr.changeKind, `changeKind ${or.changeKind} → ${nr.changeKind}`);
      cmp(f("tooltip"), or.tooltip, nr.tooltip);
      if ((or.forever ?? null) !== (nr.forever ?? null)) cmp(f("forever"), or.forever, nr.forever, ws(or.forever) === ws(nr.forever) ? "forever text whitespace" : "forever text");
      cmp(f("foreverByClass"), or.foreverByClass, nr.foreverByClass);
      cmp(f("classic.status"), or.classic.status, nr.classic.status);
      cmp(f("classic.name"), or.classic.name, nr.classic.name);
      const tk = classicTextKind(or.classic.text, nr.classic.text);
      if (tk) cmp(f("classic.text"), or.classic.text, nr.classic.text, `classic text: ${tk}`);
      cmp(f("classic.otherRaces"), or.classic.otherRaces, nr.classic.otherRaces);
      cmp(f("classicSpellId"), or.classicSpellId, nr.classicSpellId);
      cmp(f("races"), or.races, nr.races);
    }
    for (const nr of n.racials) if (!o.racials.some((x) => x.id === nr.id || x.name === nr.name)) cmp(`racial ${nr.name}`, null, nr.id, "racial added");
    report.races[o.id] = { changes };
  }
  for (const n of next.races) if (!old.races.some((o) => o.id === n.id)) count("race added");

  md.push(`Races: ${old.races.length} → ${next.races.length}; ids ${set(old.races.map((r) => r.id)) === set(next.races.map((r) => r.id)) ? "identical" : "**differ**"}.`, "");
  md.push(`Dropped top-level fields: ${droppedTop.join(", ") || "none"}; race fields: ${DROPPED.race.join(", ")}; racial fields: ${DROPPED.racial.join(", ")}.`, "");
  md.push("Kinds: " + (Object.entries(report.kinds).map(([k, v]) => `${k} ${v}`).join("; ") || "none"), "");
  for (const [field, c] of Object.entries(report.top)) md.push(`- ${field} [${c.kind}]: ${json(c.old)} → ${json(c.new)}`);
  md.push("");
  for (const [id, r] of Object.entries(report.races)) {
    md.push(`## ${id}`, "");
    if (r.removed) md.push("- removed");
    for (const c of r.changes ?? []) md.push(`- ${c.field} [${c.kind}]: ${json(c.old)} → ${json(c.new)}`);
    md.push("");
  }
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "races-diff.md"), `${md.join("\n")}\n`);
  fs.writeFileSync(path.join(outDir, "races-diff.json"), `${JSON.stringify(report, null, 2)}\n`);
  console.log(`\nRaces diff (${path.relative(repoRoot, path.join(outDir, "races-diff.md"))}):`);
  console.log(`  ${Object.entries(report.kinds).map(([k, v]) => `${k} ${v}`).join("; ") || "no changes"}`);
  return report;
}
