// The committed races dataset against a freshly generated one (usually a new client build): race
// ids, names, factions, icons and classes, then each race's racials (paired by id, then name)
// field by field, and the Classic racials each race lost. Writes <outDir>/races-diff.md and .json
// and prints a summary. Run through `npm run diff:races` (scripts/scrape/races-client.mjs --diff).

import fs from "node:fs";
import path from "node:path";

const json = (v) => JSON.stringify(v ?? null, (_k, x) => (x && typeof x === "object" && !Array.isArray(x) ? Object.fromEntries(Object.entries(x).sort(([a], [b]) => a.localeCompare(b))) : x));
const set = (xs) => json([...(xs ?? [])].sort());
const ws = (s) => (s ?? "").replace(/\s+/g, " ").trim();

/** How two texts differ: null when equal. */
function textKind(a, b) {
  if ((a ?? null) === (b ?? null)) return null;
  if (!a || !b) return a ? "dropped" : "added";
  if (ws(a) === ws(b)) return "whitespace";
  return "wording or numbers";
}

const build = (d) => `${d.meta?.foreverBuild ?? "?"} + Classic Era ${d.meta?.classicBuild ?? "?"}`;

export function diffRaces({ old, next, against, outDir, repoRoot }) {
  const report = { against, builds: { old: build(old), new: build(next) }, top: {}, races: {}, kinds: {} };
  const count = (k) => (report.kinds[k] = (report.kinds[k] ?? 0) + 1);
  const md = [
    "# Races: committed dataset vs fresh generation",
    "",
    `Generated by \`npm run diff:races\` against ${against}. Races are paired by id, racials by id (then name).`,
    "",
    `Build ${build(old)} → ${build(next)}.`,
    "",
  ];

  const top = (field, a, b, kind = field) => {
    if (json(a) !== json(b)) {
      report.top[field] = { kind, old: a, new: b };
      count(kind);
    }
  };
  top("classOrder", old.classOrder, next.classOrder, "class order");
  for (const cls of new Set([...Object.keys(old.simClassAvailability), ...Object.keys(next.simClassAvailability)]))
    for (const side of ["forever", "classic"]) {
      const a = old.simClassAvailability[cls]?.[side];
      const b = next.simClassAvailability[cls]?.[side];
      if (set(a) !== set(b)) top(`simClassAvailability.${cls}.${side}`, a, b, "sim class availability");
      else if (json(a) !== json(b)) top(`simClassAvailability.${cls}.${side}`, a, b, "sim class availability order");
    }
  const combo = (c) => `${c.raceId}/${c.class}`;
  if (set(old.newCombos.map(combo)) !== set(next.newCombos.map(combo))) top("newCombos", old.newCombos.map(combo), next.newCombos.map(combo), "new race/class pairs");
  else if (json(old.newCombos.map(combo)) !== json(next.newCombos.map(combo))) top("newCombos", old.newCombos.map(combo), next.newCombos.map(combo), "new race/class pairs order");

  const newById = new Map(next.races.map((r) => [r.id, r]));
  for (const o of old.races) {
    const n = newById.get(o.id);
    const changes = [];
    if (!n) {
      count("race removed");
      report.races[o.id] = { removed: true };
      continue;
    }
    const cmp = (field, a, b, kind = field) => {
      if (json(a) !== json(b)) {
        changes.push({ field, kind, old: a ?? null, new: b ?? null });
        count(kind);
      }
    };
    for (const f of ["name", "baseName", "faction", "icon", "chrRacesId", "newInForever"]) cmp(f, o[f], n[f]);
    for (const f of ["forever", "classic", "addedInForever", "removedInForever"]) {
      if (set(o.classes[f]) !== set(n.classes[f])) cmp(`classes.${f}`, o.classes[f], n.classes[f]);
      else if (json(o.classes[f]) !== json(n.classes[f])) cmp(`classes.${f}`, o.classes[f], n.classes[f], "class list order");
    }
    cmp("removedRacials", (o.removedRacials ?? []).map((x) => x.name).sort(), (n.removedRacials ?? []).map((x) => x.name).sort(), "removed racials");
    const oldIds = o.racials.map((x) => x.id);
    const newIds = n.racials.map((x) => x.id);
    if (set(oldIds) === set(newIds) && json(oldIds) !== json(newIds)) cmp("racial order", oldIds, newIds);
    for (const or of o.racials) {
      const nr = n.racials.find((x) => x.id === or.id) ?? n.racials.find((x) => x.name === or.name);
      if (!nr) {
        cmp(`racial ${or.name}`, or.id, null, "racial removed");
        continue;
      }
      const f = (field) => `${or.name}: ${field}`;
      for (const k of ["id", "name", "icon", "spellIds", "passive", "changeLabel", "tooltip", "foreverByClass", "classicSpellId", "races"]) cmp(f(k), or[k], nr[k]);
      cmp(f("changeKind"), or.changeKind, nr.changeKind, `changeKind ${or.changeKind} → ${nr.changeKind}`);
      const fk = textKind(or.forever, nr.forever);
      if (fk) cmp(f("forever"), or.forever, nr.forever, `forever text: ${fk}`);
      for (const k of ["status", "name", "tooltip", "otherRaces"]) cmp(f(`classic.${k}`), or.classic?.[k], nr.classic?.[k]);
      const ck = textKind(or.classic?.text, nr.classic?.text);
      if (ck) cmp(f("classic.text"), or.classic?.text, nr.classic?.text, `classic text: ${ck}`);
    }
    for (const nr of n.racials) if (!o.racials.some((x) => x.id === nr.id || x.name === nr.name)) cmp(`racial ${nr.name}`, null, nr.id, "racial added");
    report.races[o.id] = { changes };
  }
  for (const n of next.races) if (!old.races.some((o) => o.id === n.id)) count("race added");

  md.push(`Races: ${old.races.length} → ${next.races.length}; ids ${set(old.races.map((r) => r.id)) === set(next.races.map((r) => r.id)) ? "identical" : "**differ**"}.`, "");
  md.push("Kinds: " + (Object.entries(report.kinds).map(([k, v]) => `${k} ${v}`).join("; ") || "none"), "");
  for (const [field, c] of Object.entries(report.top)) md.push(`- ${field} [${c.kind}]: ${json(c.old)} → ${json(c.new)}`);
  md.push("");
  for (const [id, r] of Object.entries(report.races)) {
    if (!r.removed && !r.changes.length) continue;
    md.push(`## ${id}`, "");
    if (r.removed) md.push("- removed");
    for (const c of r.changes ?? []) md.push(`- ${c.field} [${c.kind}]: ${json(c.old)} → ${json(c.new)}`);
    md.push("");
  }
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "races-diff.md"), `${md.join("\n")}\n`);
  fs.writeFileSync(path.join(outDir, "races-diff.json"), `${JSON.stringify(report, null, 2)}\n`);
  console.log(`\nRaces diff against ${against} (${path.relative(repoRoot, path.join(outDir, "races-diff.md"))}):`);
  console.log(`  ${Object.entries(report.kinds).map(([k, v]) => `${k} ${v}`).join("; ") || "no changes"}`);
  return report;
}
