// The committed spellbooks against freshly generated ones (usually a new client build), spell by
// spell and rank by rank: tab, level, status, races, ranks and every rank field on both sides.
// Differences are sorted into kinds. Writes <outDir>/spells-diff.md and .json and prints a
// summary. Run through `npm run diff:spells` (scripts/scrape/spells-client.mjs --diff).

import fs from "node:fs";
import path from "node:path";

const json = (v) => JSON.stringify(v ?? null, (_k, x) => (x && typeof x === "object" && !Array.isArray(x) ? Object.fromEntries(Object.entries(x).sort(([a], [b]) => a.localeCompare(b))) : x));
const ws = (s) => (s ?? "").replace(/\s+/g, " ").trim();
const norm = (s) => (s ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");

/** How two tooltips differ: null when equal. */
function textKind(old, next) {
  if ((old ?? null) === (next ?? null)) return null;
  if (old == null) return "text added";
  if (next == null) return "text dropped";
  if (ws(old) === ws(next)) return "whitespace";
  const numbers = (s) => s.match(/\d+(?:\.\d+)?/g) ?? [];
  if (json(numbers(old)) !== json(numbers(next))) return "numbers";
  return "wording";
}

/** Rank fields compared one by one; `text` is compared by textKind. */
const RANK_FIELDS = ["spellId", "level", "rankLabel", "icon", "school", "cost", "castTime", "cooldown", "range", "requires", "forms"];

function rankChanges(o, n, side) {
  const out = [];
  if (!o && !n) return out;
  if (!o || !n) {
    out.push({ field: `${side}`, kind: o ? `${side} rank dropped` : `${side} rank added`, old: o?.spellId ?? null, new: n?.spellId ?? null });
    return out;
  }
  for (const field of RANK_FIELDS) if (json(o[field]) !== json(n[field])) out.push({ field: `${side}.${field}`, kind: `${side}.${field}`, old: o[field] ?? null, new: n[field] ?? null });
  const tk = textKind(o.text, n.text);
  if (tk) out.push({ field: `${side}.text`, kind: `${side}.text: ${tk}`, old: o.text, new: n.text });
  return out;
}

/** Pair old and new rank rows: by Forever spell id, then Classic spell id, then rank number. */
function pairRanks(oldRanks, newRanks) {
  const pairs = [];
  const used = new Set();
  const key = (r) => [r.forever?.spellId ?? null, r.classic?.spellId ?? null];
  for (const o of oldRanks) {
    const [of, oc] = key(o);
    let n = newRanks.find((x) => !used.has(x) && of !== null && x.forever?.spellId === of);
    n ??= newRanks.find((x) => !used.has(x) && of === null && oc !== null && x.classic?.spellId === oc && !x.forever);
    n ??= newRanks.find((x) => !used.has(x) && o.rank !== null && x.rank === o.rank);
    if (n) used.add(n);
    pairs.push({ o, n: n ?? null });
  }
  for (const n of newRanks) if (!used.has(n)) pairs.push({ o: null, n });
  return pairs;
}

const build = (d) => `${d.meta?.foreverBuild ?? "?"} + Classic Era ${d.meta?.classicBuild ?? "?"}`;

export function diffSpells({ pairs, against, outDir, repoRoot }) {
  const report = { against, classes: {}, kinds: {} };
  const md = [
    "# Spellbooks: committed dataset vs fresh generation",
    "",
    `Generated by \`npm run diff:spells\` against ${against}. Spells are paired by name, ranks by Forever spell id (then Classic spell id, then rank number).`,
    "",
  ];
  for (const { cls, old, next } of pairs) {
    const newByName = new Map(next.spells.map((s) => [norm(s.name), s]));
    const kinds = {};
    const count = (k) => {
      kinds[k] = (kinds[k] ?? 0) + 1;
      report.kinds[k] = (report.kinds[k] ?? 0) + 1;
    };
    const spells = [];
    const seen = new Set();
    for (const o of old.spells) {
      const n = newByName.get(norm(o.name));
      if (!n) {
        spells.push({ name: o.name, removed: true });
        count("spell removed");
        continue;
      }
      seen.add(n.id);
      const changes = [];
      const cmp = (field, a, b) => {
        if (json(a) !== json(b)) changes.push({ field, kind: field, old: a ?? null, new: b ?? null });
      };
      for (const f of ["id", "tab", "icon", "level", "status", "races", "maxRank", "isTalent", "grantedByTalent", "classic"]) cmp(f, o[f], n[f]);
      for (const { o: or, n: nr } of pairRanks(o.ranks, n.ranks)) {
        const label = `rank ${nr?.rank ?? or?.rank ?? "-"} (${nr?.forever?.spellId ?? or?.forever?.spellId ?? "x"}/${nr?.classic?.spellId ?? or?.classic?.spellId ?? "x"})`;
        if (!or) {
          changes.push({ field: label, kind: nr.forever ? "rank pair added (Forever)" : "rank pair added (Classic-only rank)", old: null, new: [nr.forever?.spellId ?? null, nr.classic?.spellId ?? null] });
          continue;
        }
        if (!nr) {
          changes.push({ field: label, kind: "rank pair dropped", old: [or.forever?.spellId ?? null, or.classic?.spellId ?? null], new: null });
          continue;
        }
        if ((or.rank ?? null) !== (nr.rank ?? null)) changes.push({ field: `${label} rank`, kind: "pair rank number", old: or.rank, new: nr.rank });
        if (json(or.differences) !== json(nr.differences)) changes.push({ field: `${label} differences`, kind: "Forever-vs-Classic differences", old: or.differences, new: nr.differences });
        for (const c of [...rankChanges(or.forever, nr.forever, "forever"), ...rankChanges(or.classic, nr.classic, "classic")]) changes.push({ ...c, field: `${label} ${c.field}` });
      }
      for (const c of changes) count(c.kind);
      if (changes.length) spells.push({ name: n.name, changes });
    }
    const added = next.spells.filter((s) => !seen.has(s.id)).map((s) => s.name);
    for (const _ of added) count("spell added");
    const missing = { old: old.missing.map((m) => m.name), new: next.missing.map((m) => m.name) };
    report.classes[cls] = {
      builds: { old: build(old), new: build(next) },
      counts: { old: old.counts, new: next.counts },
      tabs: { old: old.tabs, new: next.tabs },
      statuses: { old: tally(old.spells.map((s) => s.status)), new: tally(next.spells.map((s) => s.status)) },
      kinds,
      added,
      missing,
      spells,
    };
    md.push(`## ${cls}`, "");
    md.push(`Build ${build(old)} → ${build(next)}.`, "");
    md.push(`${old.spells.length} → ${next.spells.length} spells. Counts ${json(old.counts)} → ${json(next.counts)}.`, "");
    md.push(`Statuses: ${json(report.classes[cls].statuses.old)} → ${json(report.classes[cls].statuses.new)}`, "");
    if (json(old.tabs) !== json(next.tabs)) md.push(`Tabs: ${json(old.tabs)} → ${json(next.tabs)}`, "");
    md.push(`Not in Forever: ${missing.old.join(", ") || "none"} → ${missing.new.join(", ") || "none"}`, "");
    md.push(`Spells added: ${added.join(", ") || "none"}.`, "");
    md.push("Kinds: " + (Object.entries(kinds).map(([k, v]) => `${k} ${v}`).join("; ") || "none"), "");
    for (const s of spells) {
      md.push(`### ${s.name}`, "");
      if (s.removed) md.push("- removed", "");
      for (const c of s.changes ?? []) md.push(`- ${c.field} [${c.kind}]: ${json(c.old)} → ${json(c.new)}`);
      md.push("");
    }
  }
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "spells-diff.md"), `${md.join("\n")}\n`);
  fs.writeFileSync(path.join(outDir, "spells-diff.json"), `${JSON.stringify(report, null, 2)}\n`);
  console.log(`\nSpellbooks diff against ${against} (${path.relative(repoRoot, path.join(outDir, "spells-diff.md"))}):`);
  for (const [cls, r] of Object.entries(report.classes)) {
    console.log(`  ${cls}: ${r.counts.old.total} → ${r.counts.new.total} spells; statuses ${json(r.statuses.old)} → ${json(r.statuses.new)}`);
    console.log(`    ${Object.entries(r.kinds).map(([k, v]) => `${k} ${v}`).join("; ") || "no changes"}`);
  }
  return report;
}

function tally(xs) {
  const out = {};
  for (const x of xs) out[x] = (out[x] ?? 0) + 1;
  return out;
}
