// The buff catalogue: raid buffs, target debuffs and consumables for the warrior specs
// (docs/mechanics/buffs-debuffs-consumables.md). Paladin- and druid-only entries (spell power,
// mana, Holy debuffs) arrive with those specs. World buffs never exist here (decision D8).
//
// Each entry is a UI-facing BuffDefinition plus its effects and the presets that include it
// (buffs doc §6.2 and §6.3). Values are Forever's; the few that differ in Classic Era read the
// rule profile.
import type { BuffDefinition, BuffPreset, SpecId } from '../types'
import type { EffectList } from './types'

const DOC = 'docs/mechanics/buffs-debuffs-consumables.md'

/** Who a preset gives an entry to (buffs doc §6.2: `DPS`, `Tank`, `all`; §6.3 lists specs). */
export type Audience = 'all' | 'dps' | 'tank' | readonly SpecId[]

export interface BuffSpec extends BuffDefinition {
  effects: EffectList
  presets: Partial<Record<Exclude<BuffPreset['id'], 'self'>, Audience>>
}

const WARRIOR_DPS: SpecId[] = ['warrior-fury', 'warrior-arms']
const MELEE_TANKS: SpecId[] = ['warrior-protection', 'druid-feral-bear']
const BLADED = ['sword', 'axe', 'polearm', 'dagger'] as const

export const BUFFS: BuffSpec[] = [
  // --- Raid buffs (§1.1, §1.2) ---------------------------------------------------------------
  {
    id: 'battleShout',
    name: 'Battle Shout',
    icon: 'ability_warrior_battleshout',
    category: 'raidBuff',
    group: 'Attack power',
    summary: '+139 attack power',
    providedBy: 'warrior',
    docRef: `${DOC}#11-attack-power-stats-and-crit`,
    effects: [{ kind: 'stat', stat: 'ap', value: 139 }],
    presets: { dungeon: 'all', raid: 'all', max: 'all' },
  },
  {
    id: 'blessingOfMight',
    name: 'Blessing of Might',
    icon: 'spell_holy_fistofjustice',
    category: 'raidBuff',
    group: 'Attack power',
    summary: '+133 attack power',
    providedBy: 'paladin',
    docRef: `${DOC}#11-attack-power-stats-and-crit`,
    effects: [{ kind: 'stat', stat: 'ap', value: 133 }],
    presets: { dungeon: 'dps', raid: 'all', max: 'all' },
  },
  {
    id: 'blessingOfKings',
    name: 'Blessing of Kings',
    icon: 'spell_magic_magearmor',
    category: 'raidBuff',
    group: 'Stats',
    summary: '+10% all stats',
    providedBy: 'paladin',
    docRef: `${DOC}#11-attack-power-stats-and-crit`,
    effects: [{ kind: 'mult', stat: 'allStats', pct: 10 }],
    presets: { dungeon: 'tank', raid: 'all', max: 'all' },
  },
  {
    id: 'markOfTheWild',
    name: 'Gift of the Wild',
    icon: 'spell_nature_regeneration',
    category: 'raidBuff',
    group: 'Stats',
    summary: '+16 all stats, +385 armor',
    providedBy: 'druid',
    docRef: `${DOC}#11-attack-power-stats-and-crit`,
    effects: [
      { kind: 'stat', stat: 'str', value: 16 },
      { kind: 'stat', stat: 'agi', value: 16 },
      { kind: 'stat', stat: 'sta', value: 16 },
      { kind: 'stat', stat: 'int', value: 16 },
      { kind: 'stat', stat: 'spi', value: 16 },
      { kind: 'stat', stat: 'bonusArmor', value: 385 },
    ],
    presets: { dungeon: 'all', raid: 'all', max: 'all' },
  },
  {
    id: 'powerWordFortitude',
    name: 'Prayer of Fortitude',
    icon: 'spell_holy_wordfortitude',
    category: 'raidBuff',
    group: 'Stats',
    summary: '+70 Stamina',
    providedBy: 'priest',
    docRef: `${DOC}#11-attack-power-stats-and-crit`,
    effects: [{ kind: 'stat', stat: 'sta', value: 70 }],
    presets: { dungeon: 'all', raid: 'all', max: 'all' },
  },
  {
    id: 'leaderOfThePack',
    name: 'Leader of the Pack',
    icon: 'spell_nature_unyeildingstamina',
    category: 'raidBuff',
    group: 'Crit',
    summary: '+3% crit (feral druid in your party)',
    providedBy: 'druid',
    exclusiveGroup: 'party-crit-aura',
    docRef: `${DOC}#11-attack-power-stats-and-crit`,
    effects: [{ kind: 'stat', stat: 'crit', value: 3 }],
    presets: { raid: 'dps', max: 'dps' },
  },
  {
    id: 'windfuryTotem',
    name: 'Windfury Totem',
    icon: 'spell_nature_windfury',
    category: 'raidBuff',
    group: 'Shaman totems',
    summary: '20% chance on a main-hand hit for an extra attack with +246 attack power',
    providedBy: 'shaman',
    exclusiveGroup: 'totem:air',
    docRef: `${DOC}#windfury-totem`,
    effects: (p) => [
      {
        kind: 'proc',
        proc: {
          id: 'windfury',
          name: 'Windfury Attack',
          icon: 'spell_nature_windfury',
          // Each main-hand hit, white or special, 20%; can't proc from its own chain (buffs doc, Windfury Totem).
          trigger: 'meleeLanded',
          from: 'mainHand',
          chance: { pct: 20 },
          action: { kind: 'extraAttacks', count: 1, bonusAp: p.values.windfuryAp },
          docRef: `${DOC}#windfury-totem`,
        },
      },
    ],
    presets: { raid: 'all', max: 'all' },
  },
  {
    id: 'graceOfAir',
    name: 'Grace of Air Totem',
    icon: 'spell_nature_invisibilitytotem',
    category: 'raidBuff',
    group: 'Shaman totems',
    summary: '+89 Agility',
    providedBy: 'shaman',
    exclusiveGroup: 'totem:air',
    docRef: `${DOC}#11-attack-power-stats-and-crit`,
    effects: [{ kind: 'stat', stat: 'agi', value: 89 }],
    presets: {},
  },
  {
    id: 'strengthOfEarth',
    name: 'Strength of Earth Totem',
    icon: 'spell_nature_earthbindtotem',
    category: 'raidBuff',
    group: 'Shaman totems',
    summary: '+53 Strength',
    providedBy: 'shaman',
    exclusiveGroup: 'totem:earth',
    docRef: `${DOC}#11-attack-power-stats-and-crit`,
    effects: [{ kind: 'stat', stat: 'str', value: 53 }],
    presets: { raid: 'all', max: 'all' },
  },
  {
    id: 'blessingOfSalvation',
    name: 'Blessing of Salvation',
    icon: 'spell_holy_sealofsalvation',
    category: 'raidBuff',
    group: 'Threat and defense',
    summary: '−30% threat',
    providedBy: 'paladin',
    docRef: `${DOC}#12-threat-defense-and-mana`,
    effects: [{ kind: 'threat', pct: -30 }],
    presets: { raid: 'dps', max: 'dps' },
  },
  {
    id: 'devotionAura',
    name: 'Devotion Aura',
    icon: 'spell_holy_devotionaura',
    category: 'raidBuff',
    group: 'Threat and defense',
    summary: '+735 armor',
    providedBy: 'paladin',
    docRef: `${DOC}#12-threat-defense-and-mana`,
    effects: [{ kind: 'stat', stat: 'bonusArmor', value: 735 }],
    presets: { raid: 'tank', max: 'tank' },
  },

  // --- Target debuffs (§4) -------------------------------------------------------------------
  {
    id: 'sunderArmor',
    name: 'Sunder Armor ×5',
    icon: 'ability_warrior_sunder',
    category: 'targetDebuff',
    group: 'Armor',
    summary: '−2,250 armor',
    providedBy: 'warrior',
    exclusiveGroup: 'armor-major',
    docRef: `${DOC}#41-armor-reduction`,
    effects: [{ kind: 'targetArmor', value: 2250 }],
    presets: { dungeon: 'dps', raid: 'all', max: 'all' },
  },
  {
    id: 'exposeArmor',
    name: 'Expose Armor',
    icon: 'ability_warrior_riposte',
    category: 'targetDebuff',
    group: 'Armor',
    summary: '−2,250 armor (instead of Sunder Armor)',
    providedBy: 'rogue',
    exclusiveGroup: 'armor-major',
    docRef: `${DOC}#41-armor-reduction`,
    effects: (p) => [{ kind: 'targetArmor', value: p.values.exposeArmor }],
    presets: {},
  },
  {
    id: 'faerieFire',
    name: 'Faerie Fire',
    icon: 'spell_nature_faeriefire',
    category: 'targetDebuff',
    group: 'Armor',
    summary: '−505 armor',
    providedBy: 'druid',
    docRef: `${DOC}#41-armor-reduction`,
    effects: [{ kind: 'targetArmor', value: 505 }],
    presets: { raid: 'all', max: 'all' },
  },
  {
    id: 'curseOfRecklessness',
    name: 'Curse of Recklessness',
    icon: 'spell_shadow_unholystrength',
    category: 'targetDebuff',
    group: 'Armor',
    summary: '−505 armor',
    providedBy: 'warlock',
    docRef: `${DOC}#41-armor-reduction`,
    effects: (p) => [
      { kind: 'targetArmor', value: p.values.curseOfRecklessnessArmor },
      { kind: 'bossAp', value: p.values.curseOfRecklessnessBossAp },
    ],
    presets: { raid: 'all', max: 'all' },
  },
  {
    id: 'armorShatter',
    name: 'Annihilator ×3',
    icon: 'inv_axe_12',
    category: 'targetDebuff',
    group: 'Armor',
    summary: '−495 armor (Armor Shatter from a raid member’s Annihilator)',
    docRef: `${DOC}#41-armor-reduction`,
    effects: (p) => [{ kind: 'targetArmor', value: 3 * p.values.armorShatterPerStack }],
    presets: { max: 'all' },
  },
  {
    id: 'demoralizingShout',
    name: 'Demoralizing Shout',
    icon: 'ability_warrior_warcry',
    category: 'targetDebuff',
    group: 'Boss damage',
    summary: '−196 boss attack power',
    providedBy: 'warrior',
    exclusiveGroup: 'ap-reduction',
    docRef: `${DOC}#42-other-debuffs`,
    effects: (p) => [{ kind: 'bossAp', value: -p.values.demoralizingShoutAp }],
    presets: { raid: 'tank', max: 'tank' },
  },
  {
    id: 'thunderClap',
    name: 'Thunder Clap',
    icon: 'spell_nature_thunderclap',
    category: 'targetDebuff',
    group: 'Boss damage',
    summary: 'Boss attacks 20% slower',
    providedBy: 'warrior',
    docRef: `${DOC}#42-other-debuffs`,
    effects: (p) => [{ kind: 'bossSlow', pct: 100 * p.values.thunderClapSlow }],
    presets: { raid: 'tank', max: 'tank' },
  },

  // --- Consumables (§3) ----------------------------------------------------------------------
  {
    id: 'elixirOfTheMongoose',
    name: 'Elixir of the Mongoose',
    icon: 'inv_potion_32',
    category: 'consumable',
    group: 'Elixirs',
    summary: '+25 Agility, +2% crit',
    exclusiveGroup: 'elixir:agility',
    docRef: `${DOC}#32-elixirs`,
    effects: [
      { kind: 'stat', stat: 'agi', value: 25 },
      { kind: 'stat', stat: 'crit', value: 2 },
    ],
    presets: {
      raid: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-cat', 'druid-feral-bear', 'paladin-retribution'],
      max: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-cat', 'druid-feral-bear', 'paladin-retribution'],
    },
  },
  {
    id: 'elixirOfGreaterStrength',
    name: 'Elixir of Greater Strength',
    icon: 'inv_potion_61',
    category: 'consumable',
    group: 'Elixirs',
    summary: '+25 Strength',
    exclusiveGroup: 'elixir:strength',
    docRef: `${DOC}#32-elixirs`,
    effects: [{ kind: 'stat', stat: 'str', value: 25 }],
    presets: { raid: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-cat', 'druid-feral-bear', 'paladin-retribution'] },
  },
  {
    id: 'jujuPower',
    name: 'Juju Power',
    icon: 'inv_misc_monsterscales_11',
    category: 'consumable',
    group: 'Elixirs',
    summary: '+30 Strength',
    exclusiveGroup: 'elixir:strength',
    docRef: `${DOC}#33-juju-firewater-blasted-lands-and-other-buffs`,
    effects: [{ kind: 'stat', stat: 'str', value: 30 }],
    presets: { max: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-cat', 'druid-feral-bear', 'paladin-retribution'] },
  },
  {
    id: 'elixirOfGreaterDefense',
    name: 'Elixir of Greater Defense',
    icon: 'inv_potion_66',
    category: 'consumable',
    group: 'Elixirs',
    summary: '+450 armor',
    docRef: `${DOC}#32-elixirs`,
    effects: [{ kind: 'stat', stat: 'bonusArmor', value: 450 }],
    presets: { raid: [...MELEE_TANKS, 'paladin-protection'], max: [...MELEE_TANKS, 'paladin-protection'] },
  },
  {
    id: 'elixirOfFortitude',
    name: 'Elixir of Fortitude',
    icon: 'inv_potion_43',
    category: 'consumable',
    group: 'Elixirs',
    summary: '+200 health',
    exclusiveGroup: 'health-elixir',
    docRef: `${DOC}#32-elixirs`,
    effects: [{ kind: 'stat', stat: 'health', value: 200 }],
    presets: { raid: [...MELEE_TANKS, 'paladin-protection'], max: [...MELEE_TANKS, 'paladin-protection'] },
  },
  {
    id: 'flaskOfTheTitans',
    name: 'Flask of the Titans',
    icon: 'inv_potion_62',
    category: 'consumable',
    group: 'Flasks',
    summary: '+1,200 health',
    exclusiveGroup: 'flask',
    docRef: `${DOC}#31-flasks`,
    effects: [{ kind: 'stat', stat: 'health', value: 1200 }],
    presets: { max: MELEE_TANKS },
  },
  {
    id: 'flaskOfNaturalAccuracy',
    name: 'Flask of Natural Accuracy',
    icon: 'inv_potion_97',
    category: 'consumable',
    group: 'Flasks',
    summary: '+60 Stamina; +5% hit in Hyjal and the Barrow Deeps',
    exclusiveGroup: 'flask',
    docRef: `${DOC}#31-flasks`,
    effects: [
      { kind: 'stat', stat: 'sta', value: 60 },
      { kind: 'stat', stat: 'hit', value: 5, when: { zones: ['hyjal', 'barrowDeeps'] } },
    ],
    presets: {},
  },
  {
    id: 'flaskOfNaturalAggression',
    name: 'Flask of Natural Aggression',
    icon: 'inv_potion_93',
    category: 'consumable',
    group: 'Flasks',
    summary: '+60 Stamina; +4% crit in Hyjal and the Barrow Deeps',
    exclusiveGroup: 'flask',
    docRef: `${DOC}#31-flasks`,
    effects: [
      { kind: 'stat', stat: 'sta', value: 60 },
      { kind: 'stat', stat: 'crit', value: 4, when: { zones: ['hyjal', 'barrowDeeps'] } },
    ],
    presets: {},
  },
  {
    id: 'flaskOfNaturalPrecision',
    name: 'Flask of Natural Precision',
    icon: 'inv_potion_91',
    category: 'consumable',
    group: 'Flasks',
    summary: '+60 Stamina; 5% less chance to be dodged or parried in Hyjal and the Barrow Deeps',
    exclusiveGroup: 'flask',
    docRef: `${DOC}#31-flasks`,
    effects: [
      { kind: 'stat', stat: 'sta', value: 60 },
      { kind: 'stat', stat: 'expertise', value: 5, when: { zones: ['hyjal', 'barrowDeeps'] } },
    ],
    presets: {},
  },
  {
    id: 'flaskOfNaturalSwiftness',
    name: 'Flask of Natural Swiftness',
    icon: 'inv_potion_95',
    category: 'consumable',
    group: 'Flasks',
    summary: '+60 Stamina; +5% haste in Hyjal and the Barrow Deeps',
    exclusiveGroup: 'flask',
    docRef: `${DOC}#31-flasks`,
    effects: [
      { kind: 'stat', stat: 'sta', value: 60 },
      { kind: 'haste', pct: 5, when: { zones: ['hyjal', 'barrowDeeps'] } },
    ],
    presets: {},
  },
  {
    id: 'winterfallFirewater',
    name: 'Winterfall Firewater',
    icon: 'inv_potion_92',
    category: 'consumable',
    group: 'Other buffs',
    summary: '+35 attack power',
    exclusiveGroup: 'buff:ap-drink',
    docRef: `${DOC}#33-juju-firewater-blasted-lands-and-other-buffs`,
    effects: [{ kind: 'stat', stat: 'ap', value: 35 }],
    presets: { raid: WARRIOR_DPS },
  },
  {
    id: 'jujuMight',
    name: 'Juju Might',
    icon: 'inv_misc_monsterscales_07',
    category: 'consumable',
    group: 'Other buffs',
    summary: '+40 attack power',
    exclusiveGroup: 'buff:ap-drink',
    docRef: `${DOC}#33-juju-firewater-blasted-lands-and-other-buffs`,
    effects: [{ kind: 'stat', stat: 'ap', value: 40 }],
    presets: { max: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-cat', 'druid-feral-bear', 'paladin-retribution'] },
  },
  {
    id: 'roids',
    name: 'R.O.I.D.S.',
    icon: 'inv_stone_15',
    category: 'consumable',
    group: 'Other buffs',
    summary: '+25 Strength',
    exclusiveGroup: 'blasted-lands',
    docRef: `${DOC}#33-juju-firewater-blasted-lands-and-other-buffs`,
    effects: [{ kind: 'stat', stat: 'str', value: 25 }],
    presets: { max: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-bear', 'paladin-retribution'] },
  },
  {
    id: 'groundScorpokAssay',
    name: 'Ground Scorpok Assay',
    icon: 'inv_misc_dust_02',
    category: 'consumable',
    group: 'Other buffs',
    summary: '+25 Agility',
    exclusiveGroup: 'blasted-lands',
    docRef: `${DOC}#33-juju-firewater-blasted-lands-and-other-buffs`,
    effects: [{ kind: 'stat', stat: 'agi', value: 25 }],
    presets: { max: ['druid-feral-cat'] },
  },
  {
    id: 'rumseyRum',
    name: 'Rumsey Rum Black Label',
    icon: 'inv_drink_04',
    category: 'consumable',
    group: 'Other buffs',
    summary: '+15 Stamina',
    docRef: `${DOC}#33-juju-firewater-blasted-lands-and-other-buffs`,
    effects: [{ kind: 'stat', stat: 'sta', value: 15 }],
    presets: { max: MELEE_TANKS },
  },
  {
    id: 'smokedDesertDumplings',
    name: 'Smoked Desert Dumplings',
    icon: 'inv_misc_food_64',
    category: 'consumable',
    group: 'Food',
    summary: '+20 Strength',
    exclusiveGroup: 'food',
    docRef: `${DOC}#34-food`,
    effects: [{ kind: 'stat', stat: 'str', value: 20 }],
    presets: {
      dungeon: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-bear', 'paladin-retribution'],
      raid: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-bear', 'paladin-retribution'],
      max: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-bear', 'paladin-retribution'],
    },
  },
  {
    id: 'mightfishSteak',
    name: 'Mightfish Steak',
    icon: 'inv_misc_fish_27',
    category: 'consumable',
    group: 'Food',
    summary: '+40 attack power',
    exclusiveGroup: 'food',
    docRef: `${DOC}#34-food`,
    effects: [{ kind: 'stat', stat: 'ap', value: 40 }],
    presets: {},
  },
  {
    id: 'grilledSquid',
    name: 'Grilled Squid',
    icon: 'inv_misc_fish_13',
    category: 'consumable',
    group: 'Food',
    summary: '+1% crit',
    exclusiveGroup: 'food',
    docRef: `${DOC}#34-food`,
    effects: [{ kind: 'stat', stat: 'crit', value: 1 }],
    presets: {},
  },
  {
    id: 'denseSharpeningStone',
    name: 'Dense Sharpening Stone / Weightstone',
    icon: 'inv_stone_sharpeningstone_05',
    category: 'consumable',
    group: 'Weapon',
    summary: '+8 weapon damage on each weapon',
    docRef: `${DOC}#36-weapon-enhancements-temporary`,
    effects: [{ kind: 'tempEnchant', id: 'denseStone', priority: 1, weaponDamage: 8 }],
    presets: {
      dungeon: [...WARRIOR_DPS, 'paladin-retribution'],
      raid: [...WARRIOR_DPS, 'warrior-protection', 'paladin-retribution'],
      max: [...WARRIOR_DPS, 'warrior-protection', 'paladin-retribution'],
    },
  },
  {
    id: 'elementalSharpeningStone',
    name: 'Elemental Sharpening Stone',
    icon: 'inv_stone_02',
    category: 'consumable',
    group: 'Weapon',
    summary: '+2% crit per bladed weapon (replaces the dense stone there)',
    docRef: `${DOC}#36-weapon-enhancements-temporary`,
    effects: [{ kind: 'tempEnchant', id: 'elementalStone', priority: 2, weapons: [...BLADED], crit: 2 }],
    presets: { max: [...WARRIOR_DPS, 'warrior-protection', 'paladin-retribution'] },
  },
  {
    id: 'mightyRagePotion',
    name: 'Mighty Rage Potion',
    icon: 'inv_potion_41',
    category: 'consumable',
    group: 'Potions and bombs',
    summary: '45–75 rage and +60 Strength for 20 s, once at the start of the execute phase',
    docRef: `${DOC}#35-potions-and-runes`,
    effects: [{ kind: 'onUse', id: 'mightyRagePotion', name: 'Mighty Rage Potion' }],
    presets: {
      raid: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-bear'],
      max: [...WARRIOR_DPS, 'warrior-protection', 'druid-feral-cat', 'druid-feral-bear'],
    },
  },
  {
    id: 'jujuFlurry',
    name: 'Juju Flurry',
    icon: 'inv_misc_monsterscales_17',
    category: 'consumable',
    group: 'Potions and bombs',
    summary: '+3% attack speed for 20 s, every minute',
    docRef: `${DOC}#33-juju-firewater-blasted-lands-and-other-buffs`,
    effects: [{ kind: 'onUse', id: 'jujuFlurry', name: 'Juju Flurry' }],
    presets: { max: WARRIOR_DPS },
  },
  {
    id: 'ezThroDarkBomb',
    name: 'EZ-Thro Dark Bomb',
    icon: 'inv_misc_bomb_05',
    category: 'consumable',
    group: 'Potions and bombs',
    summary: '225–675 Fire damage, every minute',
    docRef: `${DOC}#37-engineering-and-explosives`,
    effects: [{ kind: 'onUse', id: 'ezThroDarkBomb', name: 'EZ-Thro Dark Bomb' }],
    presets: { max: WARRIOR_DPS },
  },
  {
    id: 'greaterStoneshieldPotion',
    name: 'Greater Stoneshield Potion',
    icon: 'inv_potion_69',
    category: 'consumable',
    group: 'Potions and bombs',
    summary: '+2,000 armor for 2 min',
    docRef: `${DOC}#35-potions-and-runes`,
    effects: [{ kind: 'onUse', id: 'greaterStoneshieldPotion', name: 'Greater Stoneshield Potion' }],
    presets: { max: MELEE_TANKS },
  },
]

export const BUFFS_BY_ID = new Map(BUFFS.map((b) => [b.id, b]))
