// Types for src/data/items/pre-bis.json, generated by scripts/scrape/items-client.mjs from the
// Forever and Classic Era client files. Keep in sync with the scraper (lib/item-stats.mjs
// STAT_TYPE and AURA_STAT produce `Stats` keys; lib/item-pool.mjs builds `Item`).
// See docs/data/items.md for provenance and derivation rules.

/**
 * How the item compares between the two clients: `new` has a Forever row and no Classic Era
 * row; `changed` / `unchanged` have both, and a stat, effect, requirement or set bonus differs
 * (or not; rewording a Classic equip spell as a Forever stat of the same value isn't a change);
 * `missing` has no Forever row, so its values are Classic Era's.
 */
export type ItemTab = "new" | "changed" | "unchanged" | "missing";

/** Normalized equip slot (from ItemSparse.InventoryType). */
export type ItemSlot =
  | "head"
  | "neck"
  | "shoulder"
  | "back"
  | "chest"
  | "wrist"
  | "hands"
  | "waist"
  | "legs"
  | "feet"
  | "finger"
  | "trinket"
  | "twoHand"
  | "mainHand"
  | "oneHand"
  | "offHand"
  | "shield"
  | "heldInOffHand"
  | "ranged"
  | "thrown"
  | "relic"
  /** Arrows and bullets; quivers and ammo pouches (docs/data/items.md#ammo-and-quivers). */
  | "ammo"
  | "quiver";

/** Paperdoll slot group an item can be equipped in (finger/trinket have two slots each). */
export type EquipSlot =
  | "head"
  | "neck"
  | "shoulder"
  | "back"
  | "chest"
  | "wrist"
  | "hands"
  | "waist"
  | "legs"
  | "feet"
  | "finger"
  | "trinket"
  | "mainHand"
  | "offHand"
  | "ranged"
  | "ammo"
  | "quiver";

export type ArmorType = "cloth" | "leather" | "mail" | "plate";

export type WeaponType =
  | "axe"
  | "bow"
  | "crossbow"
  | "dagger"
  | "fist"
  | "gun"
  | "mace"
  | "polearm"
  | "staff"
  | "sword"
  | "thrown"
  | "wand";

/** Weapon skill names, as used in `Item.weaponSkill` and `Weapon.skill`. */
export type WeaponSkill =
  | "Axes"
  | "Bows"
  | "Crossbows"
  | "Daggers"
  | "Fist Weapons"
  | "Guns"
  | "Maces"
  | "Polearms"
  | "Staves"
  | "Swords"
  | "Thrown"
  | "Two-Handed Axes"
  | "Two-Handed Maces"
  | "Two-Handed Swords"
  | "Unarmed"
  | "Wands";

export type DamageSchool = "Physical" | "Arcane" | "Fire" | "Frost" | "Holy" | "Nature" | "Shadow";

/**
 * Flat stat bonuses: the item's stat columns plus equip spells whose every aura is a flat stat.
 * Percentages are percentage points (1 = 1%). Classic Era gives chances as percentages
 * (`crit`, `hit`, `dodge`, ...); the Forever client rewrites most of them as ratings
 * (`critRating`, `hitRating`, ...). Both are kept as the client stores them;
 * `ItemDataMeta.ratingConversions` has the ratios measured on items both clients have.
 */
export interface Stats {
  // Primary
  strength: number;
  agility: number;
  stamina: number;
  intellect: number;
  spirit: number;

  // Defensive
  /**
   * Base armor: Forever's armor formula for the item level, quality and slot, or the Classic Era
   * row's stored armor (for fallback items; that total can include inherent extra armor).
   */
  armor: number;
  /**
   * Armor on top of `armor`: Forever's stat 50 (its tooltip adds it to the white armor line),
   * or an Equip or set-bonus "+N Armor" spell. Kept apart so armor multipliers can tell them apart.
   */
  bonusArmor: number;
  /** Classic "Increased Defense +N" (defense skill points). */
  defense: number;
  /** Forever "+N Defense Rating". */
  defenseRating: number;
  dodge: number;
  dodgeRating: number;
  parry: number;
  parryRating: number;
  /** Chance to block with a shield, %. */
  block: number;
  blockRating: number;
  blockValue: number;
  arcaneResistance: number;
  fireResistance: number;
  frostResistance: number;
  natureResistance: number;
  shadowResistance: number;

  // Physical
  attackPower: number;
  rangedAttackPower: number;
  /** Ranged attack speed %, multiplicative: a quiver's or ammo pouch's (aura 557; docs/data/items.md#ammo-and-quivers). */
  rangedAttackSpeed: number;
  /** "Attack Power in Cat, Bear, and Dire Bear forms only". */
  feralAttackPower: number;
  attackPowerVsBeasts: number;
  attackPowerVsDemons: number;
  attackPowerVsDragonkin: number;
  attackPowerVsElementals: number;
  attackPowerVsGiants: number;
  attackPowerVsHumanoids: number;
  attackPowerVsMechanical: number;
  attackPowerVsUndead: number;
  /** Classic "Improves your chance to hit by N%" (melee and ranged). */
  hit: number;
  /** Classic "Improves your chance to get a critical strike by N%" (melee and ranged). */
  crit: number;
  /**
   * Classic "... critical strike with melee attacks by N%". The client derivation files that aura
   * (52) under `crit`, so no item carries this today; the engine treats both as melee crit.
   */
  meleeCrit: number;
  /** Forever "+N Hit Rating" (replaces both melee and spell hit). */
  hitRating: number;
  /** Forever "+N Critical Strike Rating" (replaces both melee and spell crit). */
  critRating: number;
  hasteRating: number;
  expertiseRating: number;
  armorPenetration: number;
  /** Forever "+N Weapon Damage". */
  weaponDamage: number;

  // Spell
  /** Damage and healing ("Spell Power"; Classic "damage and healing done by magical spells"). */
  spellPower: number;
  /** Damage only, all schools. */
  spellDamage: number;
  /** Healing only. */
  healing: number;
  arcaneSpellDamage: number;
  fireSpellDamage: number;
  frostSpellDamage: number;
  holySpellDamage: number;
  natureSpellDamage: number;
  shadowSpellDamage: number;
  spellDamageVsBeasts: number;
  spellDamageVsDemons: number;
  spellDamageVsDragonkin: number;
  spellDamageVsElementals: number;
  spellDamageVsGiants: number;
  spellDamageVsHumanoids: number;
  spellDamageVsMechanical: number;
  spellDamageVsUndead: number;
  spellHit: number;
  spellCrit: number;
  spellPenetration: number;

  // Regeneration
  /** Mana per 5 sec (Classic "Restores N mana per 5 sec", Forever "+N Mana Regeneration"). */
  mp5: number;
  /** Classic "Restores N health per 5 sec". */
  hp5: number;
  /** Forever "+N Health Regeneration"; not the same unit as `hp5` (see docs/data/items.md). */
  healthRegen: number;
}

export type StatKey = keyof Stats;

export interface Weapon {
  /** Null only if the client has no damage table row for the weapon. */
  min: number | null;
  max: number | null;
  /** Seconds. */
  speed: number;
  dps: number | null;
  school: DamageSchool;
  /** The weapon skill this weapon uses (null for types without one). */
  skill: WeaponSkill | null;
  /** Extra damage ("+1 - 22 Frost Damage"; Classic Era rows only). */
  extraDamage?: { min: number; max: number; school: DamageSchool | null }[];
}

export interface VerbatimEffect {
  /**
   * The tooltip line, rendered from the spell's description, e.g. "Chance on hit: Blasts a
   * target for 150 Frost damage." (docs/data/items.md#effect-and-set-bonus-text).
   */
  raw: string;
  /**
   * The spell behind the line (ItemEffect.SpellID). Read from the Forever client whenever it has
   * the spell, fallback items included (docs/data/items.md#effects-of-fallback-items).
   */
  spellId: number;
}

export interface UseEffect extends VerbatimEffect {
  /** The item's cooldown, else its category's, from the client (ItemEffect or the spell). */
  cooldownSec?: number;
}

export interface Requirement {
  kind: "reputation" | "skill" | "pvpRank" | "other";
  /** The tooltip line, e.g. "Requires Darkspear Raiders - Honored". */
  text: string;
  faction?: string;
  standing?: string;
  skill?: string;
  /** Skill rank, or the PvP rank (1 Private / Scout … 14 Grand Marshal / High Warlord). */
  level?: number;
}

export interface SetBonus {
  pieces: number;
  /** The bonus spell (ItemSetSpell.SpellID). */
  spellId: number;
  /** The bonus spell's description, without the "(N) Set: " prefix. */
  text: string;
  /** Present when the bonus spell's every aura is a flat stat. */
  parsed?: Partial<Stats>;
  /** Present when the bonus is a weapon skill bonus. */
  weaponSkill?: Partial<Record<WeaponSkill, number>>;
}

export interface ItemSet {
  name: string;
  /** Number of pieces (`itemIds.length`). */
  size: number | null;
  /** The set's pieces (ItemSet.ItemID), any quality or level, in or out of the pool. */
  itemIds: number[];
  /**
   * From Forever's ItemSet and ItemSetSpell when Forever has the set, even if every pooled piece
   * falls back to Classic Era stats; else Classic Era's.
   */
  bonuses: SetBonus[];
  bonusesFrom: "forever" | "classic" | null;
}

export interface RatingConversion {
  /** Classic stat keys the rating replaced. */
  replaces: StatKey[];
  unit: string;
  /** Most common rating / old value ratio. */
  ratingPerUnit: number;
  /** Items showing that ratio. */
  samples: number;
  /** Other ratios seen, with counts. */
  otherRatios: Record<string, number>;
}

/** Spec keys used by the curated pre-raid BiS lists (scripts/scrape/pre-raid-bis.json). */
export type PreRaidBisSpec =
  | "warrior-fury"
  | "warrior-arms"
  | "warrior-protection"
  | "druid-feral-cat"
  | "druid-feral-bear"
  | "druid-balance"
  | "paladin-retribution"
  | "paladin-protection"
  | "shaman-enhancement"
  | "shaman-elemental"
  | "rogue-combat"
  | "rogue-assassination"
  | "rogue-subtlety"
  | "mage-fire"
  | "mage-frost"
  | "mage-arcane"
  | "warlock-destruction"
  | "warlock-affliction"
  | "warlock-demonology"
  | "priest-shadow"
  | "hunter-marksmanship"
  | "hunter-beast-mastery"
  | "hunter-survival";

/** Slot keys used by the pre-raid BiS lists: paperdoll slots, plus `twoHand` and `relic`. */
export type PreRaidBisSlot =
  | "head"
  | "neck"
  | "shoulder"
  | "back"
  | "chest"
  | "wrist"
  | "hands"
  | "waist"
  | "legs"
  | "feet"
  | "finger"
  | "trinket"
  | "mainHand"
  | "offHand"
  | "twoHand"
  | "ranged"
  | "relic";

export interface PreRaidBisEntry {
  spec: PreRaidBisSpec;
  slot: PreRaidBisSlot;
  /** 1 = the guide's best in slot, 2+ = its alternatives (finger/trinket: two are worn). */
  rank: number;
}

export interface PreRaidBisSource {
  title: string;
  /** The guide's original (2019–2021 Classic) URL. */
  url: string;
  /** Wayback Machine copy that was read; the live page has since been rewritten. */
  archivedUrl: string;
  /** Date of that copy, YYYY-MM-DD. */
  snapshot: string;
}

/** A spell whose description couldn't be rendered (or is empty), and where it is used. */
export interface DescriptionGap {
  spellId: number;
  build: "forever" | "classic";
  name?: string;
  /** The variables the renderer couldn't resolve. */
  tokens?: string[];
  /** "item <id>" or "set <id>". */
  usedBy: string[];
}

export interface ItemDataMeta {
  /** The wago.tools API endpoint the client files come from. */
  source: string;
  scraper: string;
  /** wago.tools product of the Forever client, `wow_classic_beta`. */
  product: string;
  foreverBuild: string;
  /** The build's creation date in wago.tools' build list (YYYY-MM-DD), whichever build is cached as latest; null only if the list lacks the build. */
  foreverBuildDate: string | null;
  /** wago.tools product of the fallback client, `wow_classic_era`. */
  classicProduct: string;
  classicBuild: string;
  /** Tables (and game tables) read from each build → FileDataID. */
  tables: { forever: Record<string, number>; classic: Record<string, number> };
  wowDbDefs: { repository: string; commit: string };
  /** The latest download time of the files read. */
  scrapedAt: string;
  /**
   * Kept: equippable AND ((quality in `qualities` AND (`reqLevel[0]` <= required level <=
   * `reqLevel[1]` OR item level >= `minItemLevel`)) OR listed in `includeList`) AND (id <
   * `maxClassicItemId` OR new in Forever), the last clause being the guard against Season of
   * Discovery items. `rule` spells it out.
   */
  filter: {
    rule: string;
    qualities: number[];
    reqLevel: [number, number];
    minItemLevel: number | null;
    /**
     * The ranged supplies' own rule (arrows, bullets, quivers and ammo pouches;
     * docs/data/items.md#ammo-and-quivers): these qualities, this required-level range.
     */
    supplies: { qualities: number[]; reqLevel: [number, number] };
    equippableOnly: true;
    maxClassicItemId: number;
    /** Items that pass the rule but are dropped as unobtainable, id → reason. */
    excludedItemIds: Record<string, string>;
    /** Developer rows (test, deprecated, monster items) left out by name. */
    excludedNamePattern: string;
    /** Repo path of the curated pre-raid BiS lists. */
    includeList: string | null;
  };
  counts: {
    items: number;
    byTab: Record<ItemTab, number>;
    sets: number;
    statsFrom: { forever: number; classic: number };
  };
  /**
   * New Forever items that no client build carries yet (seen only through server hotfixes).
   * They join the pool on their own once a build ships their rows.
   */
  noClientRow: { id: number; name: string }[];
  /** The curated Classic Era pre-raid BiS lists (see docs/data/items.md#pre-raid-bis-lists). */
  preRaidBis: {
    file: string | null;
    specs: Partial<Record<PreRaidBisSpec, { name: string; source: PreRaidBisSource; note?: string }>>;
    /** Distinct item ids on the lists. */
    listedItems: number;
    /**
     * Items a list dropped, kept in the pool with no rank so saved setups and share links that wear
     * them keep them (the file's `kept`).
     */
    kept: number[];
    /** Listed pool items (each counted once): items on at least one list by their own id. */
    inPool: number;
    /**
     * Pool items that take a list's entry from a listed faction twin without being listed themselves
     * (docs/data/items.md#faction-twins).
     */
    twinsListed: number;
    /** Pool items that are there only because of the lists (they fail the quality/level rule). */
    addedByList: number;
    /** Listed items with no row in either client. */
    notInData: { id: number; name: string }[];
  };
  /** Effect and set-bonus texts by how they were produced. */
  descriptionCoverage: {
    rendered: number;
    /** Conditional stat bonuses with an empty description, described from their auras. */
    generated: number;
    /** A variable couldn't be rendered: a plain description instead. */
    fallback: number;
    /** Empty descriptions, which the game doesn't show either. */
    hidden: number;
    fallbackSpells: DescriptionGap[];
    hiddenSpells: DescriptionGap[];
  };
  ratingConversions: Partial<Record<StatKey, RatingConversion>>;
  /**
   * Fallback items' effects (decision D6, docs/data/items.md#effects-of-fallback-items): the
   * `items` with effect or stat spells, how many take the Forever client's item effects, and
   * how many of their `spells` are read from the Forever client.
   */
  fallbackEffects: { items: number; effectsFromForever: number; spells: number; spellsFromForever: number };
}

export interface Item {
  id: number;
  name: string;
  /** Icon file name (the build's file list), e.g. "inv_helmet_36". */
  icon: string;
  /** 2 = Uncommon, 3 = Rare, 4 = Epic. */
  quality: number;
  itemLevel: number;
  /** 0 = no level requirement. */
  reqLevel: number;
  tab: ItemTab;
  /** The item's name in Classic Era when Forever renamed it. */
  classicName: string | null;
  /** False when the Forever client has no row for the item (decision D6). */
  foreverData: boolean;
  /** "client" when the values are the Forever client's; null without Forever data. */
  foreverSource: "client" | null;
  /**
   * Which client's row `stats`, `weapon` and set come from. A "classic" item's effects are the
   * Forever client's wherever it has them: its spells, and its item effects when Forever links
   * any (docs/data/items.md#effects-of-fallback-items).
   */
  statsFrom: "forever" | "classic";
  slot: ItemSlot;
  equipSlots: EquipSlot[];
  /** The client's item class: armor, weapons, and the ranged supplies (arrows and bullets, quivers and ammo pouches). */
  itemClass: "Armor" | "Weapon" | "Projectile" | "Quiver";
  /** The client's subclass name, e.g. "Plate", "One-Handed Swords", "Miscellaneous", "Shield", "Idol". */
  itemSubclass: string;
  armorType: ArmorType | null;
  weaponType: WeaponType | null;
  /** "BoP", "BoE", "BoU" or "Quest"; null when the item doesn't bind. */
  binding: string | null;
  /** "Unique", or any Unique-Equipped limit. */
  unique: boolean;
  uniqueEquipped: { group: string | null; max: number } | null;
  /** Class names the item is restricted to; null when any class can use it. */
  classes: string[] | null;
  /** Race names the item is restricted to; null when any race can use it. */
  races: string[] | null;
  requirements: Requirement[];
  stats: Partial<Stats>;
  weapon: Weapon | null;
  weaponSkill: Partial<Record<WeaponSkill, number>> | null;
  /** Equip spells whose auras are part of `stats` and `weaponSkill` (sorted; [] for none). */
  statSpellIds: number[];
  /** "Chance on hit:" effects, and Equip effects that fire on an event. */
  procs: VerbatimEffect[];
  useEffects: UseEffect[];
  /** Equip effects that aren't flat stats (class/ability effects, run speed, zone bonuses, ...). */
  otherEquip: VerbatimEffect[];
  /** Key into `ItemData.sets`. */
  setId: string | null;
  /** Where the item drops. Always null: the client's Encounter Journal ships empty. */
  source: null;
  /**
   * Where this item appears on the curated Classic Era pre-raid BiS lists; [] if nowhere. A list
   * names one side's item, and its faction twin takes the same entry (docs/data/items.md#faction-twins).
   */
  preRaidBis: PreRaidBisEntry[];
  /**
   * The pool's items whose client rows match this one's on everything but their names, price and
   * what binds them to a side or class (docs/data/items.md#faction-twins). `factionTwin`
   * (src/features/character/faction-gear.ts) picks the other faction's from these.
   */
  twins: number[];
  /** Copper. */
  sellPrice: number | null;
  /** The item's flavor text. */
  flavor: string | null;
  /** Classic Era values of changed items, for comparison. */
  classic: {
    stats: Partial<Stats>;
    weapon: Weapon | null;
    weaponSkill: Partial<Record<WeaponSkill, number>> | null;
  } | null;
  /**
   * Classic Era's innate shield block value (its ShieldBlockRegular game table), on shields that
   * fall back to Classic Era stats. Not in `stats.blockValue`: the Forever client has no innate
   * block value, so a fallback shield would otherwise outrank a Forever one on missing data.
   */
  classicShieldBlockValue?: number;
  /**
   * An arrow's or bullet's damage per second, from ItemDamageAmmo[item level].Quality[quality] (both
   * clients; Forever's ItemSparse has none), and which weapons fire it: arrows for bows and crossbows,
   * bullets for guns (docs/data/items.md#ammo-and-quivers). Only on ammo.
   */
  ammo?: { dps: number; projectile: "arrow" | "bullet" };
  /** What the generator noticed about the item (fallback, unknown stat types). */
  notes: string[];
}

export interface ItemData {
  meta: ItemDataMeta;
  sets: Record<string, ItemSet>;
  items: Item[];
}
