// Types for src/data/items/pre-bis.json, generated by scripts/scrape/items.mjs.
// Keep in sync with the scraper (its STAT_KEYS set mirrors `Stats`).
// See docs/data/items.md for provenance and parsing rules.

/** Which foreverchanges.pro /items tab the item came from. */
export type ItemTab = "new" | "changed" | "unchanged" | "missing";

/** Normalized equip slot (the slot label in the item's tooltip). */
export type ItemSlot =
  | "head"
  | "neck"
  | "shoulder"
  | "back"
  | "chest"
  | "wrist"
  | "hands"
  | "waist"
  | "legs"
  | "feet"
  | "finger"
  | "trinket"
  | "twoHand"
  | "mainHand"
  | "oneHand"
  | "offHand"
  | "shield"
  | "heldInOffHand"
  | "ranged"
  | "thrown"
  | "relic";

/** Paperdoll slot group an item can be equipped in (finger/trinket have two slots each). */
export type EquipSlot =
  | "head"
  | "neck"
  | "shoulder"
  | "back"
  | "chest"
  | "wrist"
  | "hands"
  | "waist"
  | "legs"
  | "feet"
  | "finger"
  | "trinket"
  | "mainHand"
  | "offHand"
  | "ranged";

export type ArmorType = "cloth" | "leather" | "mail" | "plate";

export type WeaponType =
  | "axe"
  | "bow"
  | "crossbow"
  | "dagger"
  | "fist"
  | "gun"
  | "mace"
  | "polearm"
  | "staff"
  | "sword"
  | "thrown"
  | "wand";

/** Weapon skill names, as used in `Item.weaponSkill` and `Weapon.skill`. */
export type WeaponSkill =
  | "Axes"
  | "Bows"
  | "Crossbows"
  | "Daggers"
  | "Fist Weapons"
  | "Guns"
  | "Maces"
  | "Polearms"
  | "Staves"
  | "Swords"
  | "Thrown"
  | "Two-Handed Axes"
  | "Two-Handed Maces"
  | "Two-Handed Swords"
  | "Unarmed"
  | "Wands";

export type DamageSchool = "Physical" | "Arcane" | "Fire" | "Frost" | "Holy" | "Nature" | "Shadow";

/**
 * Flat stat bonuses from a tooltip. Percentages are percentage points (1 = 1%).
 * Classic Era tooltips give chances as percentages (`crit`, `hit`, `dodge`, ...);
 * the Forever client rewrites most of them as ratings (`critRating`, `hitRating`,
 * ...). Both are kept as written; `ItemDataMeta.ratingConversions` has the ratios
 * measured on changed items.
 */
export interface Stats {
  // Primary
  strength: number;
  agility: number;
  stamina: number;
  intellect: number;
  spirit: number;

  // Defensive
  /** White armor value on the item. */
  armor: number;
  /** Green "+N Armor" (Equip or set bonus) on top of `armor`. */
  bonusArmor: number;
  /** Classic "Increased Defense +N" (defense skill points). */
  defense: number;
  /** Forever "+N Defense Rating". */
  defenseRating: number;
  dodge: number;
  dodgeRating: number;
  parry: number;
  parryRating: number;
  /** Chance to block with a shield, %. */
  block: number;
  blockRating: number;
  blockValue: number;
  arcaneResistance: number;
  fireResistance: number;
  frostResistance: number;
  natureResistance: number;
  shadowResistance: number;

  // Physical
  attackPower: number;
  rangedAttackPower: number;
  /** "Attack Power in Cat, Bear, and Dire Bear forms only". */
  feralAttackPower: number;
  attackPowerVsBeasts: number;
  attackPowerVsDemons: number;
  attackPowerVsDragonkin: number;
  attackPowerVsElementals: number;
  attackPowerVsGiants: number;
  attackPowerVsHumanoids: number;
  attackPowerVsMechanical: number;
  attackPowerVsUndead: number;
  /** Classic "Improves your chance to hit by N%" (melee and ranged). */
  hit: number;
  /** Classic "Improves your chance to get a critical strike by N%" (melee and ranged). */
  crit: number;
  /** Classic "... critical strike with melee attacks by N%" (set bonuses). */
  meleeCrit: number;
  /** Forever "+N Hit Rating" (replaces both melee and spell hit). */
  hitRating: number;
  /** Forever "+N Critical Strike Rating" (replaces both melee and spell crit). */
  critRating: number;
  hasteRating: number;
  expertiseRating: number;
  armorPenetration: number;
  /** Forever "+N Weapon Damage". */
  weaponDamage: number;

  // Spell
  /** Damage and healing ("Spell Power"; Classic "damage and healing done by magical spells"). */
  spellPower: number;
  /** Damage only, all schools. */
  spellDamage: number;
  /** Healing only. */
  healing: number;
  arcaneSpellDamage: number;
  fireSpellDamage: number;
  frostSpellDamage: number;
  holySpellDamage: number;
  natureSpellDamage: number;
  shadowSpellDamage: number;
  spellDamageVsBeasts: number;
  spellDamageVsDemons: number;
  spellDamageVsDragonkin: number;
  spellDamageVsElementals: number;
  spellDamageVsGiants: number;
  spellDamageVsHumanoids: number;
  spellDamageVsMechanical: number;
  spellDamageVsUndead: number;
  spellHit: number;
  spellCrit: number;
  spellPenetration: number;

  // Regeneration
  /** Mana per 5 sec (Classic "Restores N mana per 5 sec", Forever "+N Mana Regeneration"). */
  mp5: number;
  /** Classic "Restores N health per 5 sec". */
  hp5: number;
  /** Forever "+N Health Regeneration"; not the same unit as `hp5` (see docs/data/items.md). */
  healthRegen: number;
}

export type StatKey = keyof Stats;

export interface Weapon {
  /** Null only if neither client gives a damage range. */
  min: number | null;
  max: number | null;
  /** Seconds. */
  speed: number;
  dps: number | null;
  school: DamageSchool;
  /** The weapon skill this weapon uses (null for types without one). */
  skill: WeaponSkill | null;
  /** "+N - M <School> Damage" lines. */
  extraDamage?: { min: number; max: number; school: DamageSchool }[];
}

export interface VerbatimEffect {
  /** The full tooltip line, e.g. "Chance on hit: Blasts a target for 150 Frost damage." */
  raw: string;
}

export interface UseEffect extends VerbatimEffect {
  /** Parsed from "(N Min Cooldown)" etc., when present. */
  cooldownSec?: number;
}

export interface Requirement {
  kind: "reputation" | "skill" | "other";
  /** The tooltip line, e.g. "Requires Darkspear Raiders - Honored". */
  text: string;
  faction?: string;
  standing?: string;
  skill?: string;
  level?: number;
}

export interface SourceEntry {
  /** Boss, NPC or object name. */
  name: string;
  /** Link on foreverchanges.pro, e.g. https://foreverchanges.pro/dungeons/blackrock-depths#general-angerforge */
  url: string | null;
  /** Further text, e.g. the dungeon name. */
  details: string[];
  /** Drop chance in percent, when shown as a percentage. */
  chance: number | null;
  /** The chance text when it isn't a plain percentage. */
  chanceText: string | null;
  /** Tooltip on the chance, e.g. "Drop chance in Classic". */
  chanceLabel: string | null;
}

export interface SourceGroup {
  /** Heading on the item page, e.g. "Dungeon drop, in Classic". */
  label: string;
  entries: SourceEntry[];
}

export interface SetBonus {
  pieces: number;
  /** Bonus text without the "(N) Set: " prefix. */
  text: string;
  /** Present when the whole bonus is a flat stat bonus. */
  parsed?: Partial<Stats>;
  /** Present when the bonus is a weapon skill bonus. */
  weaponSkill?: Partial<Record<WeaponSkill, number>>;
}

export interface ItemSet {
  name: string;
  /** Piece count from the tooltip's "Name (0/N)" line, if any piece in the dataset shows it. */
  size: number | null;
  /** Every item id the site lists with this set id (any quality/level, all tabs). */
  itemIds: number[];
  /** Bonuses from a Forever tooltip when any piece has one, else from Classic. */
  bonuses: SetBonus[];
  bonusesFrom: "forever" | "classic" | null;
}

export interface RatingConversion {
  /** Classic stat keys the rating replaced on changed items. */
  replaces: StatKey[];
  unit: string;
  /** Most common rating / old value ratio. */
  ratingPerUnit: number;
  /** Items showing that ratio. */
  samples: number;
  /** Other ratios seen, with counts. */
  otherRatios: Record<string, number>;
}

/** Spec keys used by the curated pre-raid BiS lists (scripts/scrape/pre-raid-bis.json). */
export type PreRaidBisSpec =
  | "warrior-fury"
  | "warrior-arms"
  | "warrior-protection"
  | "druid-feral-cat"
  | "druid-feral-bear"
  | "paladin-retribution"
  | "paladin-protection";

/** Slot keys used by the pre-raid BiS lists: paperdoll slots, plus `twoHand` and `relic`. */
export type PreRaidBisSlot =
  | "head"
  | "neck"
  | "shoulder"
  | "back"
  | "chest"
  | "wrist"
  | "hands"
  | "waist"
  | "legs"
  | "feet"
  | "finger"
  | "trinket"
  | "mainHand"
  | "offHand"
  | "twoHand"
  | "ranged"
  | "relic";

export interface PreRaidBisEntry {
  spec: PreRaidBisSpec;
  slot: PreRaidBisSlot;
  /** 1 = the guide's best in slot, 2+ = its alternatives (finger/trinket: two are worn). */
  rank: number;
}

export interface PreRaidBisSource {
  title: string;
  /** The guide's original (2019–2021 Classic) URL. */
  url: string;
  /** Wayback Machine copy that was read; the live page has since been rewritten. */
  archivedUrl: string;
  /** Date of that copy, YYYY-MM-DD. */
  snapshot: string;
}

export interface ItemDataMeta {
  /** The list page the dataset corresponds to. */
  source: string;
  /** The static JSON files behind that page. */
  dataFiles: string[];
  scrapedAt: string;
  foreverBuild: string;
  classicBuild: string;
  foreverBuildDate: string;
  scraper: string;
  /**
   * Kept: quality in `qualities` AND equippable AND (`reqLevel[0]` <= required level <=
   * `reqLevel[1]` OR item level >= `minItemLevel`, whatever the required level, including
   * none). `rule` spells it out. Every item outside the "new" tab has an id below
   * `maxClassicItemId` (the guard against Season of Discovery items). Items on the curated
   * pre-raid BiS lists in `includeList` are kept whatever their quality or level.
   */
  filter: {
    rule: string;
    qualities: number[];
    reqLevel: [number, number];
    minItemLevel: number | null;
    equippableOnly: true;
    maxClassicItemId: number;
    /** Items that pass the rule but are dropped as unobtainable, id → reason. */
    excludedItemIds: Record<string, string>;
    /** Repo path of the curated pre-raid BiS lists, or null when off. */
    includeList: string | null;
  };
  counts: { items: number; byTab: Record<ItemTab, number>; sets: number };
  /** The curated Classic Era pre-raid BiS lists (see docs/data/items.md#pre-raid-bis-lists). */
  preRaidBis: {
    file: string | null;
    specs: Partial<Record<PreRaidBisSpec, { name: string; source: PreRaidBisSource; note?: string }>>;
    /** Distinct item ids on the lists. */
    listedItems: number;
    /** Pool items on at least one list. */
    inPool: number;
    /** Pool items that are there only because of the lists (they fail the quality/level rule). */
    addedByList: number;
    /** Listed items found in none of the site's four tab files. */
    notInData: { id: number; name: string }[];
  };
  /** Tooltip lines of the stat-source tooltip, by how they were handled. */
  parseCoverage: { lines: number; structured: number; verbatim: number; unparsed: number };
  ratingConversions: Partial<Record<StatKey, RatingConversion>>;
}

export interface Item {
  id: number;
  name: string;
  /** Icon name; image at https://foreverchanges.pro/icon/<icon>.jpg */
  icon: string;
  /** 3 = Rare, 4 = Epic. */
  quality: number;
  itemLevel: number;
  /** 0 = no level requirement. */
  reqLevel: number;
  tab: ItemTab;
  /** For "new" items rebuilt from a Classic item under a new id: the old id. */
  rebuiltFromId: number | null;
  /** The item's name in Classic when Forever renamed it. */
  classicName: string | null;
  /** False for "No Forever data yet" items. */
  foreverData: boolean;
  /**
   * Where the Forever tooltip comes from: the beta client's item data, or (for items the
   * client holds no stats for) what players recorded in game. Null without Forever data.
   */
  foreverSource: "client" | "seenInGame" | null;
  /** Which tooltip `stats`, `weapon`, effects and set come from. */
  statsFrom: "forever" | "classic";
  slot: ItemSlot;
  equipSlots: EquipSlot[];
  itemClass: "Armor" | "Weapon";
  /** Decoded subclass, e.g. "Plate", "One-Handed Swords", "Miscellaneous", "Shield", "Idol". */
  itemSubclass: string;
  armorType: ArmorType | null;
  weaponType: WeaponType | null;
  /** "BoP", "BoE", "BoU", "Soulbound" or "Quest". */
  binding: string | null;
  /** "Unique" or any "Unique-Equipped" line. */
  unique: boolean;
  uniqueEquipped: { group: string | null; max: number } | null;
  classes: string[] | null;
  requirements: Requirement[];
  stats: Partial<Stats>;
  weapon: Weapon | null;
  weaponSkill: Partial<Record<WeaponSkill, number>> | null;
  /** "Chance on hit:" lines and "Equip: Chance ..." lines. */
  procs: VerbatimEffect[];
  useEffects: UseEffect[];
  /** Equip lines that aren't flat stats (class/ability effects, run speed, ...). */
  otherEquip: VerbatimEffect[];
  /** Key into `ItemData.sets`. */
  setId: string | null;
  /** "Where it comes from" on the item page; null when the page has none. */
  source: SourceGroup[] | null;
  /** Where this item appears on the curated Classic Era pre-raid BiS lists; [] if nowhere. */
  preRaidBis: PreRaidBisEntry[];
  /** Copper. */
  sellPrice: number | null;
  flavor: string | null;
  /** Classic Era values for changed (and rebuilt) items, for comparison. */
  classic: {
    stats: Partial<Stats>;
    weapon: Weapon | null;
    weaponSkill: Partial<Record<WeaponSkill, number>> | null;
  } | null;
  notes: string[];
  /** Tooltip lines the parser didn't recognize. */
  unparsed: string[];
  tooltip: { forever: string[] | null; classic: string[] | null };
}

export interface ItemData {
  meta: ItemDataMeta;
  sets: Record<string, ItemSet>;
  items: Item[];
}
